import sys
import unittest
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from src.futures_workflow.registry import build_asset_family_registry, build_dataset_catalog, family_status_counts


class RegistryTests(unittest.TestCase):
    def test_asset_family_registry_includes_exchange_derivatives(self):
        families = build_asset_family_registry()
        family_map = {item.family_id: item for item in families}
        self.assertIn("platform_metadata", family_map)
        self.assertEqual(family_map["platform_metadata"].status, "implemented")
        self.assertIn("instrument_master", family_map["platform_metadata"].implemented_datasets)
        self.assertIn("daily_ohlcv", family_map["platform_metadata"].implemented_datasets)
        self.assertIn("trading_calendar", family_map["platform_metadata"].implemented_datasets)
        self.assertIn("yield_curves", family_map["platform_metadata"].implemented_datasets)
        self.assertIn("research_metrics", family_map["platform_metadata"].implemented_datasets)
        self.assertIn("factor_signals", family_map["platform_metadata"].implemented_datasets)
        self.assertIn("strategy_backtests", family_map["platform_metadata"].implemented_datasets)
        self.assertIn("paper_portfolios", family_map["platform_metadata"].implemented_datasets)
        self.assertIn("quality_diagnostics", family_map["platform_metadata"].implemented_datasets)
        self.assertIn("scheduler_runs", family_map["platform_metadata"].implemented_datasets)
        self.assertIn("research_reports", family_map["platform_metadata"].implemented_datasets)
        self.assertIn("ml_model_runs", family_map["platform_metadata"].implemented_datasets)
        self.assertIn("ml_predictions", family_map["platform_metadata"].implemented_datasets)
        self.assertIn("ml_feature_importance", family_map["platform_metadata"].implemented_datasets)
        self.assertIn("model_diagnostics", family_map["platform_metadata"].implemented_datasets)
        self.assertIn("backtest_input_quality", family_map["platform_metadata"].implemented_datasets)
        self.assertIn("experiment_runs", family_map["platform_metadata"].implemented_datasets)
        self.assertIn("factor_performance", family_map["platform_metadata"].implemented_datasets)
        self.assertIn("stress_test_results", family_map["platform_metadata"].implemented_datasets)
        self.assertIn("artifact_manifest", family_map["platform_metadata"].implemented_datasets)
        self.assertIn("dataset_quality_scores", family_map["platform_metadata"].implemented_datasets)
        self.assertIn("report_artifacts", family_map["platform_metadata"].implemented_datasets)
        self.assertIn("exchange_derivatives_cn", family_map)
        self.assertEqual(family_map["exchange_derivatives_cn"].status, "implemented")
        self.assertIn("options_daily_quotes", family_map["exchange_derivatives_cn"].implemented_datasets)

    def test_asset_family_registry_keeps_planned_families_explicit(self):
        families = build_asset_family_registry()
        counts = family_status_counts(families)
        self.assertGreaterEqual(counts.get("partially_implemented", 0), 1)
        family_map = {item.family_id: item for item in families}
        self.assertEqual(family_map["fx_money_market_cn"].status, "partially_implemented")
        self.assertIn("fx_reference_rates", family_map["fx_money_market_cn"].implemented_datasets)
        self.assertIn("rmb_middle_rates", family_map["fx_money_market_cn"].implemented_datasets)
        self.assertIn("fx_spot_quotes", family_map["fx_money_market_cn"].implemented_datasets)
        self.assertIn("fx_pair_quotes", family_map["fx_money_market_cn"].implemented_datasets)
        self.assertIn("fx_swap_quotes", family_map["fx_money_market_cn"].implemented_datasets)
        self.assertIn("fx_c_swap_curve", family_map["fx_money_market_cn"].implemented_datasets)
        self.assertIn("fx_quotes", family_map["fx_money_market_cn"].implemented_datasets)
        self.assertIn("reserve_reference_series", family_map["fx_money_market_cn"].implemented_datasets)
        self.assertIn("bse_equities_spot_snapshot", family_map["equities_funds_cn"].implemented_datasets)
        self.assertIn("lof_spot_snapshot", family_map["equities_funds_cn"].implemented_datasets)
        self.assertIn("open_fund_nav_snapshot", family_map["equities_funds_cn"].implemented_datasets)
        self.assertIn("money_market_fund_snapshot", family_map["equities_funds_cn"].implemented_datasets)
        self.assertIn("convertible_bond_spot_snapshot", family_map["equities_funds_cn"].implemented_datasets)
        self.assertIn("fund_nav", family_map["equities_funds_cn"].implemented_datasets)
        self.assertIn("reits_quotes", family_map["equities_funds_cn"].implemented_datasets)
        self.assertEqual(family_map["bonds_rates_cn"].status, "partially_implemented")
        self.assertIn("interbank_bond_deal_snapshot", family_map["bonds_rates_cn"].implemented_datasets)
        self.assertIn("yield_curve_points", family_map["bonds_rates_cn"].implemented_datasets)
        self.assertIn("cn_us_treasury_yields", family_map["bonds_rates_cn"].implemented_datasets)
        self.assertIn("bond_master", family_map["bonds_rates_cn"].implemented_datasets)
        self.assertIn("bond_quotes", family_map["bonds_rates_cn"].implemented_datasets)
        self.assertIn("loan_prime_rates", family_map["bonds_rates_cn"].implemented_datasets)
        self.assertIn("repo_reference_rates", family_map["bonds_rates_cn"].implemented_datasets)
        self.assertIn("sse_bond_deal_summary", family_map["bonds_rates_cn"].implemented_datasets)
        self.assertIn("sse_bond_cash_summary", family_map["bonds_rates_cn"].implemented_datasets)
        self.assertEqual(family_map["precious_metals_spot_cn"].status, "partially_implemented")
        self.assertIn("precious_metal_reference_quotes", family_map["precious_metals_spot_cn"].implemented_datasets)
        self.assertIn("sge_spot_daily_quotes", family_map["precious_metals_spot_cn"].implemented_datasets)
        self.assertIn("commodity_spot_quotes", family_map["precious_metals_spot_cn"].implemented_datasets)
        self.assertEqual(family_map["commodity_energy_cn"].status, "partially_implemented")
        self.assertIn("carbon_market_snapshot", family_map["commodity_energy_cn"].implemented_datasets)
        self.assertEqual(family_map["crypto_global_observation"].status, "partially_implemented")
        self.assertIn("crypto_global_snapshot", family_map["crypto_global_observation"].implemented_datasets)
        self.assertIn("crypto_assets", family_map["crypto_global_observation"].implemented_datasets)
        self.assertIn("crypto_bitcoin_holdings_public", family_map["crypto_global_observation"].implemented_datasets)
        self.assertIn("crypto_cme_bitcoin_report", family_map["crypto_global_observation"].implemented_datasets)
        self.assertIn("crypto_daily_quotes", family_map["crypto_global_observation"].implemented_datasets)
        self.assertIn("crypto_derivatives_public", family_map["crypto_global_observation"].implemented_datasets)
        self.assertIn("crypto_global_quotes", family_map["crypto_global_observation"].implemented_datasets)

    def test_dataset_catalog_covers_contracts_and_views(self):
        catalog = build_dataset_catalog()
        datasets = {item["dataset"] for item in catalog}
        self.assertIn("instrument_master", datasets)
        self.assertIn("bond_master", datasets)
        self.assertIn("bond_quotes", datasets)
        self.assertIn("fx_quotes", datasets)
        self.assertIn("commodity_spot_quotes", datasets)
        self.assertIn("crypto_global_quotes", datasets)
        self.assertIn("daily_ohlcv", datasets)
        self.assertIn("fund_nav", datasets)
        self.assertIn("reits_quotes", datasets)
        self.assertIn("trading_calendar", datasets)
        self.assertIn("yield_curves", datasets)
        self.assertIn("validation_results", datasets)
        self.assertIn("source_health", datasets)
        self.assertIn("contracts_snapshot", datasets)
        self.assertIn("options_chain_matrix", datasets)
        self.assertIn("crypto_bitcoin_holdings_public", datasets)
        self.assertIn("crypto_cme_bitcoin_report", datasets)
        self.assertIn("crypto_daily_quotes", datasets)
        self.assertIn("research_metrics", datasets)
        self.assertIn("factor_signals", datasets)
        self.assertIn("strategy_backtests", datasets)
        self.assertIn("paper_portfolios", datasets)
        self.assertIn("quality_diagnostics", datasets)
        self.assertIn("scheduler_runs", datasets)
        self.assertIn("research_reports", datasets)
        self.assertIn("ml_model_runs", datasets)
        self.assertIn("ml_predictions", datasets)
        self.assertIn("ml_feature_importance", datasets)
        self.assertIn("model_diagnostics", datasets)
        self.assertIn("backtest_input_quality", datasets)
        self.assertIn("experiment_runs", datasets)
        self.assertIn("factor_performance", datasets)
        self.assertIn("stress_test_results", datasets)
        self.assertIn("artifact_manifest", datasets)
        self.assertIn("dataset_quality_scores", datasets)
        self.assertIn("report_artifacts", datasets)


if __name__ == "__main__":
    unittest.main()
