from zoneinfo import ZoneInfo


ASIA_SHANGHAI = ZoneInfo("Asia/Shanghai")

STANDARD_FIELDS = [
    "trade_date",
    "exchange",
    "variety_code",
    "variety_name",
    "contract",
    "delivery_month",
    "open",
    "high",
    "low",
    "close",
    "prev_settlement",
    "settlement",
    "change_close",
    "change_settlement",
    "volume",
    "open_interest",
    "open_interest_change",
    "turnover",
    "source_url",
    "source_type",
    "retrieved_at",
    "raw_path",
]

OPTIONS_STANDARD_FIELDS = [
    "trade_date",
    "exchange",
    "product_code",
    "product_name",
    "contract",
    "underlying_exchange",
    "underlying_kind",
    "underlying_product_code",
    "underlying_contract",
    "option_type",
    "strike_price",
    "exercise_type",
    "expire_date",
    "last_trade_date",
    "open",
    "high",
    "low",
    "close",
    "prev_settlement",
    "settlement",
    "change_close",
    "change_settlement",
    "volume",
    "open_interest",
    "open_interest_change",
    "turnover",
    "delta",
    "implied_volatility",
    "exercise_volume",
    "source_url",
    "source_type",
    "retrieved_at",
    "raw_path",
]

DERIVATIVES_STANDARD_FIELDS = [
    "trade_date",
    "instrument_type",
    "exchange",
    "product_code",
    "product_name",
    "contract",
    "underlying_exchange",
    "underlying_kind",
    "underlying_product_code",
    "underlying_contract",
    "delivery_month",
    "expire_date",
    "option_type",
    "strike_price",
    "exercise_type",
    "open",
    "high",
    "low",
    "close",
    "prev_settlement",
    "settlement",
    "change_close",
    "change_settlement",
    "volume",
    "open_interest",
    "open_interest_change",
    "turnover",
    "delta",
    "implied_volatility",
    "exercise_volume",
    "source_url",
    "source_type",
    "retrieved_at",
    "raw_path",
]

CONTRACTS_STANDARD_FIELDS = [
    "trade_date",
    "instrument_type",
    "exchange",
    "product_code",
    "product_name",
    "contract",
    "contract_status",
    "list_date",
    "expire_date",
    "last_trade_date",
    "contract_multiplier",
    "quote_unit",
    "price_tick",
    "delivery_type",
    "exercise_type",
    "option_type",
    "strike_price",
    "underlying_exchange",
    "underlying_kind",
    "underlying_product_code",
    "underlying_contract",
    "source_url",
    "source_type",
    "retrieved_at",
    "raw_path",
]

OPTION_RESULTS_STANDARD_FIELDS = [
    "trade_date",
    "exchange",
    "contract",
    "underlying_contract",
    "option_type",
    "strike_price",
    "expire_date",
    "exercise_volume",
    "assignment_volume",
    "cash_settlement_amount",
    "delivery_quantity",
    "result_status",
    "source_url",
    "source_type",
    "retrieved_at",
    "raw_path",
]

FUTURES_RESULTS_STANDARD_FIELDS = [
    "trade_date",
    "exchange",
    "contract",
    "delivery_month",
    "expire_date",
    "final_settlement_price",
    "delivery_volume",
    "delivery_amount",
    "warehouse_delivery_quantity",
    "result_status",
    "source_url",
    "source_type",
    "retrieved_at",
    "raw_path",
]

OPTIONS_CHAIN_MATRIX_FIELDS = [
    "trade_date",
    "exchange",
    "underlying_contract",
    "expire_date",
    "strike_price",
    "call_contract",
    "call_close",
    "call_settlement",
    "call_volume",
    "call_open_interest",
    "call_delta",
    "call_implied_volatility",
    "put_contract",
    "put_close",
    "put_settlement",
    "put_volume",
    "put_open_interest",
    "put_delta",
    "put_implied_volatility",
]

UNDERLYING_SUMMARY_FIELDS = [
    "trade_date",
    "exchange",
    "underlying_contract",
    "underlying_kind",
    "futures_contract",
    "futures_close",
    "futures_settlement",
    "futures_volume",
    "futures_open_interest",
    "options_contract_count",
    "options_total_volume",
    "options_total_open_interest",
    "call_volume",
    "put_volume",
    "call_open_interest",
    "put_open_interest",
]

FUTURES_DATASET = "futures_daily_quotes"
OPTIONS_DATASET = "options_daily_quotes"
DERIVATIVES_DATASET = "derivatives_daily_quotes"
CONTRACTS_DATASET = "contracts_snapshot"
OPTION_RESULTS_DATASET = "options_exercise_results"
FUTURES_RESULTS_DATASET = "futures_delivery_results"
OPTIONS_CHAIN_VIEW = "options_chain_matrix"
UNDERLYING_SUMMARY_VIEW = "underlying_derivatives_summary"
EQUITIES_SNAPSHOT_DATASET = "equities_spot_snapshot"
ETF_SNAPSHOT_DATASET = "etf_spot_snapshot"
LOF_SNAPSHOT_DATASET = "lof_spot_snapshot"
OPEN_FUND_SNAPSHOT_DATASET = "open_fund_nav_snapshot"
MONEY_FUND_SNAPSHOT_DATASET = "money_market_fund_snapshot"
REITS_SNAPSHOT_DATASET = "reits_spot_snapshot"
BSE_EQUITIES_SNAPSHOT_DATASET = "bse_equities_spot_snapshot"
CONVERTIBLE_BOND_SNAPSHOT_DATASET = "convertible_bond_spot_snapshot"
SGE_SPOT_DAILY_DATASET = "sge_spot_daily_quotes"
CARBON_MARKET_SNAPSHOT_DATASET = "carbon_market_snapshot"
FX_REFERENCE_DATASET = "fx_reference_rates"
RMB_MIDDLE_RATE_DATASET = "rmb_middle_rates"
FX_SPOT_DATASET = "fx_spot_quotes"
FX_PAIR_DATASET = "fx_pair_quotes"
FX_SWAP_DATASET = "fx_swap_quotes"
FX_C_SWAP_CURVE_DATASET = "fx_c_swap_curve"
MONEY_MARKET_DATASET = "money_market_rates"
PRECIOUS_METAL_REFERENCE_DATASET = "precious_metal_reference_quotes"
RESERVE_REFERENCE_DATASET = "reserve_reference_series"
CRYPTO_GLOBAL_SNAPSHOT_DATASET = "crypto_global_snapshot"
LPR_REFERENCE_DATASET = "loan_prime_rates"
REPO_REFERENCE_DATASET = "repo_reference_rates"
CN_US_TREASURY_RATE_DATASET = "cn_us_treasury_yields"
INTERBANK_BOND_DEAL_DATASET = "interbank_bond_deal_snapshot"
INTERBANK_BOND_QUOTE_DATASET = "interbank_bond_quote_snapshot"
YIELD_CURVE_DATASET = "yield_curve_points"
SSE_BOND_DEAL_SUMMARY_DATASET = "sse_bond_deal_summary"
SSE_BOND_CASH_SUMMARY_DATASET = "sse_bond_cash_summary"
INSTRUMENT_MASTER_DATASET = "instrument_master"
VALIDATION_RESULTS_DATASET = "validation_results"
SOURCE_HEALTH_DATASET = "source_health"
RUN_HEALTH_DATASET = "run_health"
RUN_HISTORY_DATASET = "run_history"
ASSET_COVERAGE_DATASET = "asset_coverage"
COVERAGE_HISTORY_DATASET = "coverage_history"
SOURCE_TYPE_OVERVIEW_DATASET = "source_type_overview"
ISSUE_CATEGORY_OVERVIEW_DATASET = "issue_category_overview"
SOURCE_HEALTH_HISTORY_DATASET = "source_health_history"
BOND_MASTER_DATASET = "bond_master"
BOND_QUOTES_DATASET = "bond_quotes"
FX_QUOTES_DATASET = "fx_quotes"
COMMODITY_SPOT_QUOTES_DATASET = "commodity_spot_quotes"
CRYPTO_GLOBAL_QUOTES_DATASET = "crypto_global_quotes"
DAILY_OHLCV_DATASET = "daily_ohlcv"
FUND_NAV_DATASET = "fund_nav"
REITS_QUOTES_DATASET = "reits_quotes"
TRADING_CALENDAR_DATASET = "trading_calendar"
YIELD_CURVES_PLATFORM_DATASET = "yield_curves"
CRYPTO_ASSETS_DATASET = "crypto_assets"
CRYPTO_DAILY_QUOTES_DATASET = "crypto_daily_quotes"
CRYPTO_DERIVATIVES_PUBLIC_DATASET = "crypto_derivatives_public"
CRYPTO_BITCOIN_HOLDINGS_DATASET = "crypto_bitcoin_holdings_public"
CRYPTO_CME_BITCOIN_REPORT_DATASET = "crypto_cme_bitcoin_report"
RESEARCH_METRICS_DATASET = "research_metrics"
FACTOR_SIGNALS_DATASET = "factor_signals"
STRATEGY_BACKTESTS_DATASET = "strategy_backtests"
PAPER_PORTFOLIOS_DATASET = "paper_portfolios"
QUALITY_DIAGNOSTICS_DATASET = "quality_diagnostics"
SCHEDULER_RUNS_DATASET = "scheduler_runs"
RESEARCH_REPORTS_DATASET = "research_reports"
ALGORITHM_OUTPUTS_DATASET = "algorithm_outputs"
OPTION_ANALYTICS_DATASET = "option_analytics"
BOND_ANALYTICS_DATASET = "bond_analytics"
CURVE_ANALYTICS_DATASET = "curve_analytics"
RISK_METRICS_DATASET = "risk_metrics"
PORTFOLIO_ALLOCATIONS_DATASET = "portfolio_allocations"
BACKTEST_EQUITY_CURVES_DATASET = "backtest_equity_curves"
BACKTEST_POSITIONS_DATASET = "backtest_positions"
BACKTEST_TRADES_DATASET = "backtest_trades"
STRATEGY_COMPARISONS_DATASET = "strategy_comparisons"
ANOMALY_EVENTS_DATASET = "anomaly_events"
ML_MODEL_RUNS_DATASET = "ml_model_runs"
ML_PREDICTIONS_DATASET = "ml_predictions"
ML_FEATURE_IMPORTANCE_DATASET = "ml_feature_importance"
MODEL_DIAGNOSTICS_DATASET = "model_diagnostics"
BACKTEST_INPUT_QUALITY_DATASET = "backtest_input_quality"
EXPERIMENT_RUNS_DATASET = "experiment_runs"
FACTOR_PERFORMANCE_DATASET = "factor_performance"
STRESS_TEST_RESULTS_DATASET = "stress_test_results"
ARTIFACT_MANIFEST_DATASET = "artifact_manifest"
DATASET_QUALITY_SCORES_DATASET = "dataset_quality_scores"
REPORT_ARTIFACTS_DATASET = "report_artifacts"

PUBLIC_ASSET_STANDARD_FIELDS = [
    "trade_date",
    "asset_family",
    "asset_type",
    "market",
    "exchange",
    "symbol",
    "name",
    "last_price",
    "change_amount",
    "change_pct",
    "open",
    "high",
    "low",
    "prev_close",
    "volume",
    "amount",
    "source_id",
    "source_url",
    "source_type",
    "retrieved_at",
    "raw_path",
    "parser_version",
    "checksum",
    "run_id",
]

PUBLIC_REFERENCE_STANDARD_FIELDS = [
    "trade_date",
    "asset_family",
    "reference_type",
    "market",
    "exchange",
    "symbol",
    "name",
    "base_currency",
    "quote_currency",
    "tenor",
    "value",
    "change_bp",
    "unit",
    "source_id",
    "source_url",
    "source_type",
    "retrieved_at",
    "raw_path",
    "parser_version",
    "checksum",
    "run_id",
]

CRYPTO_GLOBAL_STANDARD_FIELDS = [
    "trade_date",
    "asset_family",
    "market",
    "exchange",
    "symbol",
    "name",
    "price_usd",
    "change_amount_24h",
    "change_pct_24h",
    "high_24h",
    "low_24h",
    "total_volume",
    "market_cap",
    "market_cap_rank",
    "circulating_supply",
    "total_supply",
    "max_supply",
    "source_id",
    "source_url",
    "source_type",
    "retrieved_at",
    "raw_path",
    "parser_version",
    "checksum",
    "run_id",
    "legal_note",
]

PUBLIC_BOND_STANDARD_FIELDS = [
    "trade_date",
    "asset_family",
    "dataset_type",
    "market",
    "exchange",
    "symbol",
    "name",
    "curve_name",
    "counterparty",
    "tenor",
    "price",
    "bid_price",
    "ask_price",
    "yield",
    "bid_yield",
    "ask_yield",
    "weighted_yield",
    "change_bp",
    "volume",
    "source_id",
    "source_url",
    "source_type",
    "retrieved_at",
    "raw_path",
    "parser_version",
    "checksum",
    "run_id",
]

PUBLIC_BOND_SUMMARY_FIELDS = [
    "trade_date",
    "asset_family",
    "dataset_type",
    "market",
    "exchange",
    "category",
    "name",
    "count_value",
    "amount",
    "market_value",
    "par_value",
    "source_id",
    "source_url",
    "source_type",
    "retrieved_at",
    "raw_path",
    "parser_version",
    "checksum",
    "run_id",
]

INSTRUMENT_MASTER_STANDARD_FIELDS = [
    "trade_date",
    "instrument_id",
    "asset_family",
    "market",
    "exchange",
    "instrument_type",
    "symbol",
    "name",
    "currency",
    "listing_date",
    "delisting_date",
    "status",
    "underlying_id",
    "contract_multiplier",
    "price_tick",
    "quote_unit",
    "trading_unit",
    "delivery_type",
    "exercise_type",
    "option_type",
    "strike_price",
    "expire_date",
    "last_trade_date",
    "source_id",
    "source_url",
    "source_type",
    "retrieved_at",
    "raw_path",
    "parser_version",
    "checksum",
    "run_id",
]

VALIDATION_RESULT_STANDARD_FIELDS = [
    "trade_date",
    "scope",
    "dataset",
    "source_trade_date",
    "status",
    "row_count",
    "schema_ok",
    "duplicate_keys",
    "missing_raw_paths_count",
    "completeness_ok",
    "master_data_completeness",
    "result_chain_semantics_ok",
    "contracts_latest_consistency_ok",
    "source_provenance_ok",
    "expected_markets",
    "observed_markets",
    "blocked_issue_count",
    "blocked_issues",
    "no_data_reason",
    "not_applicable_reason",
    "output_path",
    "validated_at",
]

SOURCE_HEALTH_STANDARD_FIELDS = [
    "trade_date",
    "source_id",
    "asset_family",
    "market",
    "exchange",
    "dataset",
    "source_type",
    "priority",
    "source_url",
    "last_status",
    "last_trade_date",
    "last_success_trade_date",
    "output_path",
    "issue_category",
    "issue_root_cause",
    "is_external_blocker",
    "blocked_reason",
    "message",
]

RUN_HEALTH_STANDARD_FIELDS = [
    "trade_date",
    "workflow_name",
    "scope",
    "status",
    "engineering_status",
    "updated_at",
    "checked_dates",
    "date_statuses",
    "window_statuses",
    "window_sample_counts",
    "window_sampled_dates",
    "needs_repair_dates",
    "issue_category_counts",
    "blocked_issue_count",
    "blocked_issues",
    "platform_sync_status",
    "platform_validation_status",
    "build_db_status",
    "gui_smoke_status",
    "source_id",
    "source_url",
    "source_type",
    "retrieved_at",
    "raw_path",
    "parser_version",
    "checksum",
    "run_id",
]

RUN_HISTORY_STANDARD_FIELDS = [
    "trade_date",
    "history_kind",
    "run_id",
    "scope",
    "action_name",
    "mode",
    "target",
    "window_start",
    "window_end",
    "status",
    "engineering_status",
    "elapsed_seconds",
    "item_count",
    "success_count",
    "non_success_count",
    "blocked_issue_count",
    "issue_category_counts",
    "blocked_issues",
    "updated_at",
    "source_id",
    "source_url",
    "source_type",
    "retrieved_at",
    "raw_path",
    "parser_version",
    "checksum",
]

ASSET_COVERAGE_STANDARD_FIELDS = [
    "trade_date",
    "asset_family",
    "family_label",
    "phase",
    "registry_status",
    "engineering_status",
    "runtime_status",
    "latest_trade_date",
    "latest_success_trade_date",
    "expected_dataset_count",
    "observed_dataset_count",
    "success_dataset_count",
    "non_success_dataset_count",
    "blocked_issue_count",
    "external_issue_count",
    "internal_issue_count",
    "total_row_count",
    "coverage_ratio",
    "datasets",
    "missing_datasets",
    "status_counts",
    "issue_root_cause_counts",
    "markets",
    "notes",
    "source_id",
    "source_url",
    "source_type",
    "retrieved_at",
    "raw_path",
    "parser_version",
    "checksum",
    "run_id",
]

COVERAGE_HISTORY_STANDARD_FIELDS = [
    "trade_date",
    "asset_family",
    "family_label",
    "engineering_status",
    "runtime_status",
    "coverage_ratio",
    "success_dataset_count",
    "non_success_dataset_count",
    "blocked_issue_count",
    "external_issue_count",
    "internal_issue_count",
    "total_row_count",
    "issue_root_cause_counts",
    "source_id",
    "source_url",
    "source_type",
    "retrieved_at",
    "raw_path",
    "parser_version",
    "checksum",
]

SOURCE_TYPE_OVERVIEW_STANDARD_FIELDS = [
    "trade_date",
    "source_type",
    "source_count",
    "dataset_count",
    "success_count",
    "non_success_count",
    "blocked_issue_count",
    "latest_trade_date",
    "status_counts",
    "source_ids",
    "source_id",
    "source_url",
    "source_type_origin",
    "retrieved_at",
    "raw_path",
    "parser_version",
    "checksum",
    "run_id",
]

SOURCE_HEALTH_HISTORY_STANDARD_FIELDS = [
    "trade_date",
    "source_id",
    "dataset",
    "asset_family",
    "market",
    "exchange",
    "source_type",
    "last_status",
    "issue_category",
    "issue_root_cause",
    "is_external_blocker",
    "blocked_reason",
    "message",
    "output_path",
    "recorded_at",
    "source_url",
    "raw_path",
    "parser_version",
    "checksum",
]

ISSUE_CATEGORY_OVERVIEW_STANDARD_FIELDS = [
    "trade_date",
    "issue_category",
    "source_count",
    "dataset_count",
    "blocked_issue_count",
    "latest_trade_date",
    "status_counts",
    "source_type_counts",
    "source_ids",
    "datasets",
    "source_id",
    "source_url",
    "source_type",
    "retrieved_at",
    "raw_path",
    "parser_version",
    "checksum",
    "run_id",
]

BOND_MASTER_STANDARD_FIELDS = [
    "trade_date",
    "instrument_id",
    "asset_family",
    "market",
    "exchange",
    "symbol",
    "name",
    "dataset_type",
    "bond_type",
    "issuer",
    "tenor",
    "currency",
    "maturity_date",
    "status",
    "source_id",
    "source_url",
    "source_type",
    "retrieved_at",
    "raw_path",
    "parser_version",
    "checksum",
    "run_id",
]

BOND_QUOTES_STANDARD_FIELDS = [
    "trade_date",
    "asset_family",
    "market",
    "exchange",
    "symbol",
    "name",
    "dataset_type",
    "tenor",
    "price",
    "bid_price",
    "ask_price",
    "yield",
    "bid_yield",
    "ask_yield",
    "weighted_yield",
    "change_bp",
    "volume",
    "source_id",
    "source_url",
    "source_type",
    "retrieved_at",
    "raw_path",
    "parser_version",
    "checksum",
    "run_id",
]

FX_QUOTES_STANDARD_FIELDS = [
    "trade_date",
    "asset_family",
    "market",
    "exchange",
    "symbol",
    "name",
    "quote_type",
    "base_currency",
    "quote_currency",
    "tenor",
    "value",
    "bid",
    "ask",
    "mid",
    "unit",
    "source_id",
    "source_url",
    "source_type",
    "retrieved_at",
    "raw_path",
    "parser_version",
    "checksum",
    "run_id",
]

COMMODITY_SPOT_QUOTES_STANDARD_FIELDS = [
    "trade_date",
    "asset_family",
    "market",
    "exchange",
    "symbol",
    "name",
    "commodity_type",
    "price",
    "change_amount",
    "change_pct",
    "high",
    "low",
    "volume",
    "unit",
    "source_id",
    "source_url",
    "source_type",
    "retrieved_at",
    "raw_path",
    "parser_version",
    "checksum",
    "run_id",
]

CRYPTO_GLOBAL_QUOTES_STANDARD_FIELDS = [
    "trade_date",
    "asset_family",
    "market",
    "exchange",
    "symbol",
    "name",
    "quote_type",
    "contract_type",
    "price_usd",
    "market_cap",
    "total_volume",
    "high_24h",
    "low_24h",
    "change_pct_24h",
    "source_id",
    "source_url",
    "source_type",
    "retrieved_at",
    "raw_path",
    "parser_version",
    "checksum",
    "run_id",
    "legal_note",
]

DAILY_OHLCV_STANDARD_FIELDS = [
    "trade_date",
    "instrument_id",
    "asset_family",
    "market",
    "exchange",
    "instrument_type",
    "symbol",
    "name",
    "currency",
    "open",
    "high",
    "low",
    "close",
    "pre_close",
    "settlement",
    "pre_settlement",
    "volume",
    "amount",
    "open_interest",
    "turnover_rate",
    "source_id",
    "source_url",
    "source_type",
    "retrieved_at",
    "raw_path",
    "parser_version",
    "checksum",
    "run_id",
]

FUND_NAV_STANDARD_FIELDS = [
    "trade_date",
    "instrument_id",
    "asset_family",
    "market",
    "exchange",
    "symbol",
    "name",
    "fund_type",
    "nav",
    "nav_change",
    "nav_change_pct",
    "nav_date",
    "source_id",
    "source_url",
    "source_type",
    "retrieved_at",
    "raw_path",
    "parser_version",
    "checksum",
    "run_id",
]

REITS_QUOTES_STANDARD_FIELDS = [
    "trade_date",
    "instrument_id",
    "asset_family",
    "market",
    "exchange",
    "symbol",
    "name",
    "open",
    "high",
    "low",
    "close",
    "pre_close",
    "volume",
    "amount",
    "source_id",
    "source_url",
    "source_type",
    "retrieved_at",
    "raw_path",
    "parser_version",
    "checksum",
    "run_id",
]

TRADING_CALENDAR_STANDARD_FIELDS = [
    "trade_date",
    "calendar_id",
    "asset_family",
    "market",
    "exchange",
    "is_trading_day",
    "day_status",
    "source_trade_date",
    "source_id",
    "source_url",
    "source_type",
    "retrieved_at",
    "raw_path",
    "parser_version",
    "checksum",
    "run_id",
]

YIELD_CURVES_STANDARD_FIELDS = [
    "trade_date",
    "asset_family",
    "market",
    "exchange",
    "curve_name",
    "curve_type",
    "tenor",
    "tenor_years",
    "yield",
    "change_bp",
    "source_id",
    "source_url",
    "source_type",
    "retrieved_at",
    "raw_path",
    "parser_version",
    "checksum",
    "run_id",
]

CRYPTO_ASSET_STANDARD_FIELDS = [
    "trade_date",
    "asset_family",
    "market",
    "exchange",
    "symbol",
    "name",
    "category",
    "market_cap_rank",
    "circulating_supply",
    "total_supply",
    "max_supply",
    "source_id",
    "source_url",
    "source_type",
    "retrieved_at",
    "raw_path",
    "parser_version",
    "checksum",
    "run_id",
    "legal_note",
]

CRYPTO_DAILY_QUOTE_STANDARD_FIELDS = [
    "trade_date",
    "asset_family",
    "market",
    "exchange",
    "symbol",
    "name",
    "price_usd",
    "market_cap",
    "total_volume",
    "high_24h",
    "low_24h",
    "change_pct_24h",
    "source_id",
    "source_url",
    "source_type",
    "retrieved_at",
    "raw_path",
    "parser_version",
    "checksum",
    "run_id",
    "legal_note",
]

CRYPTO_DERIVATIVE_PUBLIC_FIELDS = [
    "trade_date",
    "asset_family",
    "market",
    "exchange",
    "symbol",
    "underlying_symbol",
    "contract_type",
    "price_usd",
    "index_price_usd",
    "basis",
    "spread",
    "funding_rate",
    "open_interest_usd",
    "volume_24h_usd",
    "last_traded_at",
    "source_id",
    "source_url",
    "source_type",
    "retrieved_at",
    "raw_path",
    "parser_version",
    "checksum",
    "run_id",
    "legal_note",
]

CRYPTO_BITCOIN_HOLDING_STANDARD_FIELDS = [
    "trade_date",
    "asset_family",
    "market",
    "exchange",
    "symbol",
    "company_name_en",
    "company_name_zh",
    "region",
    "holder_category",
    "market_cap_usd",
    "btc_market_cap_ratio",
    "holding_cost_usd",
    "holding_ratio",
    "holding_btc",
    "holding_value_usd",
    "source_query_date",
    "announcement_url",
    "source_id",
    "source_url",
    "source_type",
    "retrieved_at",
    "raw_path",
    "parser_version",
    "checksum",
    "run_id",
    "legal_note",
]

CRYPTO_CME_BITCOIN_REPORT_FIELDS = [
    "trade_date",
    "asset_family",
    "market",
    "exchange",
    "commodity",
    "report_type",
    "electronic_contracts",
    "pit_contracts",
    "block_contracts",
    "volume",
    "open_interest",
    "open_interest_change",
    "source_id",
    "source_url",
    "source_type",
    "retrieved_at",
    "raw_path",
    "parser_version",
    "checksum",
    "run_id",
    "legal_note",
]

RESEARCH_METRICS_STANDARD_FIELDS = [
    "trade_date",
    "asset_family",
    "dataset",
    "metric_name",
    "metric_value",
    "metric_unit",
    "sample_count",
    "window_start",
    "window_end",
    "status",
    "reason",
    "source_dataset",
    "source_id",
    "source_url",
    "source_type",
    "retrieved_at",
    "raw_path",
    "parser_version",
    "checksum",
    "run_id",
]

FACTOR_SIGNALS_STANDARD_FIELDS = [
    "trade_date",
    "asset_family",
    "dataset",
    "symbol_or_contract",
    "factor_name",
    "factor_value",
    "signal_direction",
    "source_dataset",
    "status",
    "reason",
    "source_id",
    "source_url",
    "source_type",
    "retrieved_at",
    "raw_path",
    "parser_version",
    "checksum",
    "run_id",
]

STRATEGY_BACKTESTS_STANDARD_FIELDS = [
    "trade_date",
    "strategy_name",
    "asset_family",
    "dataset",
    "portfolio_value",
    "cash",
    "position_count",
    "daily_return",
    "cumulative_return",
    "drawdown",
    "turnover",
    "fee_bps",
    "trade_count",
    "status",
    "reason",
    "window_start",
    "window_end",
    "source_dataset",
    "source_id",
    "source_url",
    "source_type",
    "retrieved_at",
    "raw_path",
    "parser_version",
    "checksum",
    "run_id",
]

PAPER_PORTFOLIOS_STANDARD_FIELDS = [
    "trade_date",
    "strategy_name",
    "asset_family",
    "dataset",
    "portfolio_id",
    "cash",
    "market_value",
    "equity",
    "position_count",
    "trade_count",
    "positions",
    "trades",
    "status",
    "reason",
    "source_id",
    "source_url",
    "source_type",
    "retrieved_at",
    "raw_path",
    "parser_version",
    "checksum",
    "run_id",
]

QUALITY_DIAGNOSTICS_STANDARD_FIELDS = [
    "trade_date",
    "diagnostic_type",
    "asset_family",
    "dataset",
    "source_id",
    "status",
    "severity",
    "metric_name",
    "metric_value",
    "message",
    "recommendation",
    "source_url",
    "source_type",
    "retrieved_at",
    "raw_path",
    "parser_version",
    "checksum",
    "run_id",
]

SCHEDULER_RUNS_STANDARD_FIELDS = [
    "trade_date",
    "schedule_id",
    "task_name",
    "action_name",
    "enabled",
    "due_at",
    "started_at",
    "finished_at",
    "status",
    "engineering_status",
    "message",
    "result_summary",
    "next_run_at",
    "source_id",
    "source_url",
    "source_type",
    "retrieved_at",
    "raw_path",
    "parser_version",
    "checksum",
    "run_id",
]

RESEARCH_REPORTS_STANDARD_FIELDS = [
    "trade_date",
    "report_id",
    "report_type",
    "status",
    "severity",
    "markdown_path",
    "html_path",
    "summary",
    "warning_count",
    "failed_count",
    "blocked_issue_count",
    "source_id",
    "source_url",
    "source_type",
    "retrieved_at",
    "raw_path",
    "parser_version",
    "checksum",
    "run_id",
]

ALGORITHM_OUTPUTS_STANDARD_FIELDS = [
    "trade_date",
    "asset_family",
    "dataset",
    "template_name",
    "category",
    "symbol_or_contract",
    "metric_name",
    "metric_value",
    "metric_unit",
    "parameters",
    "window_start",
    "window_end",
    "status",
    "reason",
    "source_dataset",
    "source_id",
    "source_url",
    "source_type",
    "retrieved_at",
    "raw_path",
    "parser_version",
    "checksum",
    "run_id",
]

OPTION_ANALYTICS_STANDARD_FIELDS = [
    "trade_date",
    "asset_family",
    "dataset",
    "symbol_or_contract",
    "model_name",
    "option_type",
    "underlying_price",
    "strike_price",
    "time_to_expiry",
    "risk_free_rate",
    "volatility",
    "market_price",
    "model_price",
    "implied_volatility",
    "delta",
    "gamma",
    "vega",
    "theta",
    "parameters",
    "window_start",
    "window_end",
    "status",
    "reason",
    "source_dataset",
    "source_id",
    "source_url",
    "source_type",
    "retrieved_at",
    "raw_path",
    "parser_version",
    "checksum",
    "run_id",
]

BOND_ANALYTICS_STANDARD_FIELDS = [
    "trade_date",
    "asset_family",
    "dataset",
    "symbol_or_contract",
    "model_name",
    "price",
    "coupon_rate",
    "maturity_years",
    "face_value",
    "ytm",
    "duration",
    "modified_duration",
    "convexity",
    "parameters",
    "window_start",
    "window_end",
    "status",
    "reason",
    "source_dataset",
    "source_id",
    "source_url",
    "source_type",
    "retrieved_at",
    "raw_path",
    "parser_version",
    "checksum",
    "run_id",
]

CURVE_ANALYTICS_STANDARD_FIELDS = [
    "trade_date",
    "asset_family",
    "dataset",
    "curve_name",
    "model_name",
    "tenor_short",
    "tenor_long",
    "value_short",
    "value_long",
    "slope",
    "spread",
    "parameters",
    "window_start",
    "window_end",
    "status",
    "reason",
    "source_dataset",
    "source_id",
    "source_url",
    "source_type",
    "retrieved_at",
    "raw_path",
    "parser_version",
    "checksum",
    "run_id",
]

RISK_METRICS_STANDARD_FIELDS = [
    "trade_date",
    "asset_family",
    "dataset",
    "template_name",
    "portfolio_id",
    "metric_name",
    "metric_value",
    "metric_unit",
    "parameters",
    "window_start",
    "window_end",
    "status",
    "reason",
    "source_dataset",
    "source_id",
    "source_url",
    "source_type",
    "retrieved_at",
    "raw_path",
    "parser_version",
    "checksum",
    "run_id",
]

PORTFOLIO_ALLOCATIONS_STANDARD_FIELDS = [
    "trade_date",
    "portfolio_id",
    "template_name",
    "asset_family",
    "dataset",
    "symbol_or_contract",
    "weight",
    "notional",
    "parameters",
    "window_start",
    "window_end",
    "status",
    "reason",
    "source_dataset",
    "source_id",
    "source_url",
    "source_type",
    "retrieved_at",
    "raw_path",
    "parser_version",
    "checksum",
    "run_id",
]

BACKTEST_EQUITY_CURVES_STANDARD_FIELDS = [
    "trade_date",
    "strategy_name",
    "asset_family",
    "dataset",
    "portfolio_value",
    "daily_return",
    "cumulative_return",
    "drawdown",
    "turnover",
    "fee_bps",
    "slippage_bps",
    "parameters",
    "window_start",
    "window_end",
    "status",
    "reason",
    "source_dataset",
    "source_id",
    "source_url",
    "source_type",
    "retrieved_at",
    "raw_path",
    "parser_version",
    "checksum",
    "run_id",
]

BACKTEST_POSITIONS_STANDARD_FIELDS = [
    "trade_date",
    "strategy_name",
    "asset_family",
    "dataset",
    "symbol_or_contract",
    "quantity",
    "price",
    "market_value",
    "weight",
    "side",
    "parameters",
    "window_start",
    "window_end",
    "status",
    "reason",
    "source_dataset",
    "source_id",
    "source_url",
    "source_type",
    "retrieved_at",
    "raw_path",
    "parser_version",
    "checksum",
    "run_id",
]

BACKTEST_TRADES_STANDARD_FIELDS = [
    "trade_date",
    "strategy_name",
    "asset_family",
    "dataset",
    "symbol_or_contract",
    "side",
    "quantity",
    "price",
    "notional",
    "fee",
    "slippage",
    "total_cost",
    "parameters",
    "window_start",
    "window_end",
    "status",
    "reason",
    "source_dataset",
    "source_id",
    "source_url",
    "source_type",
    "retrieved_at",
    "raw_path",
    "parser_version",
    "checksum",
    "run_id",
]

STRATEGY_COMPARISONS_STANDARD_FIELDS = [
    "trade_date",
    "strategy_name",
    "benchmark_name",
    "dataset",
    "metric_name",
    "strategy_value",
    "benchmark_value",
    "difference",
    "parameters",
    "window_start",
    "window_end",
    "status",
    "reason",
    "source_dataset",
    "source_id",
    "source_url",
    "source_type",
    "retrieved_at",
    "raw_path",
    "parser_version",
    "checksum",
    "run_id",
]

ANOMALY_EVENTS_STANDARD_FIELDS = [
    "trade_date",
    "asset_family",
    "dataset",
    "source_id",
    "event_type",
    "severity",
    "metric_name",
    "metric_value",
    "threshold",
    "message",
    "recommendation",
    "source_url",
    "source_type",
    "retrieved_at",
    "raw_path",
    "parser_version",
    "checksum",
    "run_id",
]

ML_MODEL_RUNS_STANDARD_FIELDS = [
    "trade_date",
    "run_id",
    "template_name",
    "dataset",
    "asset_family",
    "target_field",
    "feature_fields",
    "train_start",
    "train_end",
    "test_start",
    "test_end",
    "tuned",
    "status",
    "reason",
    "score_metric",
    "score_value",
    "best_params",
    "source_dataset",
    "source_id",
    "source_url",
    "source_type",
    "retrieved_at",
    "raw_path",
    "parser_version",
    "checksum",
]

ML_PREDICTIONS_STANDARD_FIELDS = [
    "trade_date",
    "run_id",
    "template_name",
    "dataset",
    "asset_family",
    "symbol_or_contract",
    "prediction_date",
    "actual_value",
    "predicted_value",
    "residual",
    "status",
    "reason",
    "source_dataset",
    "source_id",
    "source_url",
    "source_type",
    "retrieved_at",
    "raw_path",
    "parser_version",
    "checksum",
]

ML_FEATURE_IMPORTANCE_STANDARD_FIELDS = [
    "trade_date",
    "run_id",
    "template_name",
    "dataset",
    "feature_name",
    "importance_value",
    "rank",
    "status",
    "reason",
    "source_dataset",
    "source_id",
    "source_url",
    "source_type",
    "retrieved_at",
    "raw_path",
    "parser_version",
    "checksum",
]

MODEL_DIAGNOSTICS_STANDARD_FIELDS = [
    "trade_date",
    "run_id",
    "template_name",
    "dataset",
    "diagnostic_type",
    "metric_name",
    "metric_value",
    "status",
    "reason",
    "source_dataset",
    "source_id",
    "source_url",
    "source_type",
    "retrieved_at",
    "raw_path",
    "parser_version",
    "checksum",
]

BACKTEST_INPUT_QUALITY_STANDARD_FIELDS = [
    "trade_date",
    "run_id",
    "strategy_name",
    "dataset",
    "asset_family",
    "symbol_or_contract",
    "issue_type",
    "severity",
    "metric_name",
    "metric_value",
    "message",
    "recommendation",
    "source_dataset",
    "source_id",
    "source_url",
    "source_type",
    "retrieved_at",
    "raw_path",
    "parser_version",
    "checksum",
]

EXPERIMENT_RUNS_STANDARD_FIELDS = [
    "trade_date",
    "run_id",
    "experiment_type",
    "template_name",
    "dataset",
    "asset_family",
    "window_start",
    "window_end",
    "status",
    "reason",
    "score_metric",
    "score_value",
    "parameters",
    "artifact_count",
    "source_dataset",
    "source_id",
    "source_url",
    "source_type",
    "retrieved_at",
    "raw_path",
    "parser_version",
    "checksum",
]

FACTOR_PERFORMANCE_STANDARD_FIELDS = [
    "trade_date",
    "factor_name",
    "dataset",
    "asset_family",
    "metric_name",
    "metric_value",
    "sample_count",
    "window_start",
    "window_end",
    "status",
    "reason",
    "source_dataset",
    "source_id",
    "source_url",
    "source_type",
    "retrieved_at",
    "raw_path",
    "parser_version",
    "checksum",
    "run_id",
]

STRESS_TEST_RESULTS_STANDARD_FIELDS = [
    "trade_date",
    "run_id",
    "template_name",
    "scenario_name",
    "dataset",
    "asset_family",
    "portfolio_id",
    "metric_name",
    "base_value",
    "stressed_value",
    "impact_value",
    "impact_pct",
    "parameters",
    "window_start",
    "window_end",
    "status",
    "reason",
    "source_dataset",
    "source_id",
    "source_url",
    "source_type",
    "retrieved_at",
    "raw_path",
    "parser_version",
    "checksum",
]

ARTIFACT_MANIFEST_STANDARD_FIELDS = [
    "trade_date",
    "run_id",
    "artifact_id",
    "artifact_type",
    "title",
    "dataset",
    "path",
    "checksum",
    "source_datasets",
    "parameters",
    "status",
    "reason",
    "source_id",
    "source_url",
    "source_type",
    "retrieved_at",
    "raw_path",
    "parser_version",
]

DATASET_QUALITY_SCORES_STANDARD_FIELDS = [
    "trade_date",
    "dataset",
    "asset_family",
    "quality_score",
    "completeness_score",
    "freshness_score",
    "source_health_score",
    "anomaly_score",
    "row_count",
    "status",
    "reason",
    "source_dataset",
    "source_id",
    "source_url",
    "source_type",
    "retrieved_at",
    "raw_path",
    "parser_version",
    "checksum",
    "run_id",
]

REPORT_ARTIFACTS_STANDARD_FIELDS = [
    "trade_date",
    "report_id",
    "artifact_id",
    "artifact_type",
    "title",
    "path",
    "status",
    "reason",
    "source_id",
    "source_url",
    "source_type",
    "retrieved_at",
    "raw_path",
    "parser_version",
    "checksum",
    "run_id",
]

DATASET_INVENTORY_DATASET = "dataset_inventory"
DATASET_FIELD_PROFILE_DATASET = "dataset_field_profile"
DATA_LINEAGE_DATASET = "data_lineage"
DATASET_SLA_RULES_DATASET = "dataset_sla_rules"
SLA_VIOLATIONS_DATASET = "sla_violations"
KNOWLEDGE_INDEX_DATASET = "knowledge_index"
ML_FEATURE_STORE_DATASET = "ml_feature_store"
ML_BENCHMARKS_DATASET = "ml_benchmarks"
ML_VALIDATION_FOLDS_DATASET = "ml_validation_folds"
ML_CLASSIFICATION_RESULTS_DATASET = "ml_classification_results"
FACTOR_EXPERIMENTS_DATASET = "factor_experiments"
PARAMETER_SCANS_DATASET = "parameter_scans"
STRATEGY_LEADERBOARD_DATASET = "strategy_leaderboard"
PORTFOLIO_EXPERIMENTS_DATASET = "portfolio_experiments"
SCENARIO_SIMULATIONS_DATASET = "scenario_simulations"
RESEARCH_PROJECTS_DATASET = "research_projects"
PROJECT_RUNS_DATASET = "project_runs"
REPRODUCIBLE_PACKAGES_DATASET = "reproducible_packages"
AGENT_TASKS_DATASET = "agent_tasks"
AGENT_STEPS_DATASET = "agent_steps"
PLUGIN_REGISTRY_DATASET = "plugin_registry"
PLUGIN_RUNS_DATASET = "plugin_runs"
RESEARCH_MEMORY_DATASET = "research_memory"
EXPERIMENT_NOTES_DATASET = "experiment_notes"
DECISION_LOG_DATASET = "decision_log"
QUALITY_GATES_DATASET = "quality_gates"
RESEARCH_READINESS_DATASET = "research_readiness"
INPUT_RISK_FLAGS_DATASET = "input_risk_flags"
TASK_QUEUE_DATASET = "task_queue"
TASK_LOGS_DATASET = "task_logs"
TASK_RETRIES_DATASET = "task_retries"
REPORT_INSIGHTS_DATASET = "report_insights"
RECOMMENDATION_ITEMS_DATASET = "recommendation_items"
MODEL_REGISTRY_DATASET = "model_registry"
FEATURE_VERSIONS_DATASET = "feature_versions"
MODEL_DRIFT_EVENTS_DATASET = "model_drift_events"

DATASET_INVENTORY_STANDARD_FIELDS = [
    "trade_date",
    "dataset",
    "asset_family",
    "market",
    "exchange",
    "file_count",
    "row_count",
    "column_count",
    "first_trade_date",
    "last_trade_date",
    "latest_file",
    "duckdb_indexed",
    "status",
    "reason",
    "source_id",
    "source_url",
    "source_type",
    "retrieved_at",
    "raw_path",
    "parser_version",
    "checksum",
    "run_id",
]

DATASET_FIELD_PROFILE_STANDARD_FIELDS = [
    "trade_date",
    "dataset",
    "field_name",
    "inferred_type",
    "non_null_count",
    "missing_count",
    "missing_ratio",
    "unique_count",
    "sample_value",
    "status",
    "reason",
    "source_id",
    "source_url",
    "source_type",
    "retrieved_at",
    "raw_path",
    "parser_version",
    "checksum",
    "run_id",
]

DATA_LINEAGE_STANDARD_FIELDS = [
    "trade_date",
    "run_id",
    "artifact_id",
    "artifact_type",
    "producer",
    "source_datasets",
    "parameters",
    "checksum",
    "path",
    "status",
    "reason",
    "source_id",
    "source_url",
    "source_type",
    "retrieved_at",
    "raw_path",
    "parser_version",
]

DATASET_SLA_RULES_STANDARD_FIELDS = [
    "trade_date",
    "dataset",
    "expected_update_time",
    "min_rows",
    "max_stale_days",
    "external_blocker_whitelist",
    "enabled",
    "status",
    "reason",
    "source_id",
    "source_url",
    "source_type",
    "retrieved_at",
    "raw_path",
    "parser_version",
    "checksum",
]

SLA_VIOLATIONS_STANDARD_FIELDS = [
    "trade_date",
    "dataset",
    "violation_type",
    "severity",
    "observed_value",
    "expected_value",
    "message",
    "status",
    "reason",
    "source_id",
    "source_url",
    "source_type",
    "retrieved_at",
    "raw_path",
    "parser_version",
    "checksum",
    "run_id",
]

KNOWLEDGE_INDEX_STANDARD_FIELDS = [
    "trade_date",
    "knowledge_id",
    "category",
    "title",
    "body",
    "tags",
    "source_path",
    "status",
    "reason",
    "source_id",
    "source_url",
    "source_type",
    "retrieved_at",
    "raw_path",
    "parser_version",
    "checksum",
    "run_id",
]

ML_FEATURE_STORE_STANDARD_FIELDS = [
    "trade_date",
    "dataset",
    "asset_family",
    "symbol_or_contract",
    "feature_name",
    "feature_value",
    "window",
    "source_field",
    "status",
    "reason",
    "source_dataset",
    "source_id",
    "source_url",
    "source_type",
    "retrieved_at",
    "raw_path",
    "parser_version",
    "checksum",
    "run_id",
]

ML_BENCHMARKS_STANDARD_FIELDS = [
    "trade_date",
    "run_id",
    "template_name",
    "dataset",
    "asset_family",
    "target_field",
    "feature_fields",
    "score_metric",
    "score_value",
    "r2",
    "mae",
    "rmse",
    "direction_accuracy",
    "sample_count",
    "feature_count",
    "elapsed_seconds",
    "rank",
    "best_params",
    "status",
    "reason",
    "source_dataset",
    "source_id",
    "source_url",
    "source_type",
    "retrieved_at",
    "raw_path",
    "parser_version",
    "checksum",
]

ML_VALIDATION_FOLDS_STANDARD_FIELDS = [
    "trade_date",
    "run_id",
    "template_name",
    "dataset",
    "fold_index",
    "method",
    "train_start",
    "train_end",
    "test_start",
    "test_end",
    "target_field",
    "feature_fields",
    "score_metric",
    "score_value",
    "sample_count",
    "status",
    "reason",
    "source_dataset",
    "source_id",
    "source_url",
    "source_type",
    "retrieved_at",
    "raw_path",
    "parser_version",
    "checksum",
]

ML_CLASSIFICATION_RESULTS_STANDARD_FIELDS = [
    "trade_date",
    "run_id",
    "template_name",
    "dataset",
    "task_name",
    "class_label",
    "prediction_count",
    "accuracy",
    "precision",
    "recall",
    "f1",
    "roc_auc",
    "confusion_matrix",
    "status",
    "reason",
    "source_dataset",
    "source_id",
    "source_url",
    "source_type",
    "retrieved_at",
    "raw_path",
    "parser_version",
    "checksum",
]

FACTOR_EXPERIMENTS_STANDARD_FIELDS = [
    "trade_date",
    "run_id",
    "factor_name",
    "dataset",
    "asset_family",
    "parameter_set",
    "ic",
    "rank_ic",
    "long_short_return",
    "win_rate",
    "turnover",
    "coverage",
    "status",
    "reason",
    "source_dataset",
    "source_id",
    "source_url",
    "source_type",
    "retrieved_at",
    "raw_path",
    "parser_version",
    "checksum",
]

PARAMETER_SCANS_STANDARD_FIELDS = [
    "trade_date",
    "run_id",
    "template_name",
    "dataset",
    "parameter_set",
    "metric_name",
    "metric_value",
    "rank",
    "status",
    "reason",
    "source_dataset",
    "source_id",
    "source_url",
    "source_type",
    "retrieved_at",
    "raw_path",
    "parser_version",
    "checksum",
]

STRATEGY_LEADERBOARD_STANDARD_FIELDS = [
    "trade_date",
    "run_id",
    "strategy_name",
    "dataset",
    "annual_return",
    "annual_volatility",
    "sharpe",
    "calmar",
    "max_drawdown",
    "win_rate",
    "turnover",
    "quality_score",
    "rank",
    "status",
    "reason",
    "source_dataset",
    "source_id",
    "source_url",
    "source_type",
    "retrieved_at",
    "raw_path",
    "parser_version",
    "checksum",
]

PORTFOLIO_EXPERIMENTS_STANDARD_FIELDS = [
    "trade_date",
    "run_id",
    "template_name",
    "dataset",
    "portfolio_id",
    "metric_name",
    "metric_value",
    "parameters",
    "status",
    "reason",
    "source_dataset",
    "source_id",
    "source_url",
    "source_type",
    "retrieved_at",
    "raw_path",
    "parser_version",
    "checksum",
]

SCENARIO_SIMULATIONS_STANDARD_FIELDS = [
    "trade_date",
    "run_id",
    "scenario_name",
    "dataset",
    "portfolio_id",
    "base_value",
    "stressed_value",
    "impact_value",
    "impact_pct",
    "parameters",
    "status",
    "reason",
    "source_dataset",
    "source_id",
    "source_url",
    "source_type",
    "retrieved_at",
    "raw_path",
    "parser_version",
    "checksum",
]

RESEARCH_PROJECTS_STANDARD_FIELDS = [
    "trade_date",
    "project_id",
    "name",
    "description",
    "status",
    "created_at",
    "updated_at",
    "source_id",
    "source_url",
    "source_type",
    "retrieved_at",
    "raw_path",
    "parser_version",
    "checksum",
]

PROJECT_RUNS_STANDARD_FIELDS = [
    "trade_date",
    "project_id",
    "run_id",
    "template_name",
    "dataset",
    "start_date",
    "end_date",
    "parameters",
    "artifact_count",
    "status",
    "reason",
    "source_id",
    "source_url",
    "source_type",
    "retrieved_at",
    "raw_path",
    "parser_version",
    "checksum",
]

REPRODUCIBLE_PACKAGES_STANDARD_FIELDS = [
    "trade_date",
    "package_id",
    "run_id",
    "path",
    "source_datasets",
    "parameters",
    "artifact_count",
    "checksum",
    "status",
    "reason",
    "source_id",
    "source_url",
    "source_type",
    "retrieved_at",
    "raw_path",
    "parser_version",
]

PLUGIN_REGISTRY_STANDARD_FIELDS = [
    "trade_date",
    "plugin_id",
    "category",
    "label",
    "inputs",
    "outputs",
    "required_datasets",
    "risk_level",
    "supports_dry_run",
    "produces_artifacts",
    "status",
    "reason",
    "source_id",
    "source_url",
    "source_type",
    "retrieved_at",
    "raw_path",
    "parser_version",
    "checksum",
    "run_id",
]

PLUGIN_RUNS_STANDARD_FIELDS = [
    "trade_date",
    "run_id",
    "plugin_id",
    "task_id",
    "step_id",
    "status",
    "engineering_status",
    "started_at",
    "finished_at",
    "elapsed_seconds",
    "inputs",
    "outputs",
    "artifacts",
    "reason",
    "source_id",
    "source_url",
    "source_type",
    "retrieved_at",
    "raw_path",
    "parser_version",
    "checksum",
]

AGENT_TASKS_STANDARD_FIELDS = [
    "trade_date",
    "task_id",
    "goal",
    "asset_family",
    "dataset",
    "start_date",
    "end_date",
    "mode",
    "report_type",
    "status",
    "engineering_status",
    "draft_plan",
    "risk_summary",
    "created_at",
    "updated_at",
    "confirmed_at",
    "run_id",
    "source_id",
    "source_url",
    "source_type",
    "retrieved_at",
    "raw_path",
    "parser_version",
    "checksum",
]

AGENT_STEPS_STANDARD_FIELDS = [
    "trade_date",
    "task_id",
    "step_id",
    "step_order",
    "plugin_id",
    "step_name",
    "category",
    "status",
    "engineering_status",
    "inputs",
    "outputs",
    "artifacts",
    "risk_level",
    "reason",
    "started_at",
    "finished_at",
    "source_id",
    "source_url",
    "source_type",
    "retrieved_at",
    "raw_path",
    "parser_version",
    "checksum",
    "run_id",
]

RESEARCH_MEMORY_STANDARD_FIELDS = [
    "trade_date",
    "memory_id",
    "task_id",
    "goal",
    "memory_type",
    "title",
    "body",
    "tags",
    "status",
    "source_id",
    "source_url",
    "source_type",
    "retrieved_at",
    "raw_path",
    "parser_version",
    "checksum",
    "run_id",
]

EXPERIMENT_NOTES_STANDARD_FIELDS = [
    "trade_date",
    "note_id",
    "task_id",
    "run_id",
    "note_type",
    "title",
    "body",
    "status",
    "source_id",
    "source_url",
    "source_type",
    "retrieved_at",
    "raw_path",
    "parser_version",
    "checksum",
]

DECISION_LOG_STANDARD_FIELDS = [
    "trade_date",
    "decision_id",
    "task_id",
    "decision_type",
    "decision",
    "rationale",
    "status",
    "decided_at",
    "source_id",
    "source_url",
    "source_type",
    "retrieved_at",
    "raw_path",
    "parser_version",
    "checksum",
    "run_id",
]

QUALITY_GATES_STANDARD_FIELDS = [
    "trade_date",
    "gate_id",
    "task_id",
    "dataset",
    "asset_family",
    "start_date",
    "end_date",
    "gate_status",
    "severity",
    "sample_count",
    "missing_ratio",
    "source_health_status",
    "message",
    "recommendation",
    "source_id",
    "source_url",
    "source_type",
    "retrieved_at",
    "raw_path",
    "parser_version",
    "checksum",
    "run_id",
]

RESEARCH_READINESS_STANDARD_FIELDS = [
    "trade_date",
    "readiness_id",
    "task_id",
    "dataset",
    "asset_family",
    "readiness_status",
    "score",
    "gate_status",
    "risk_flags",
    "message",
    "source_id",
    "source_url",
    "source_type",
    "retrieved_at",
    "raw_path",
    "parser_version",
    "checksum",
    "run_id",
]

INPUT_RISK_FLAGS_STANDARD_FIELDS = [
    "trade_date",
    "flag_id",
    "task_id",
    "dataset",
    "risk_type",
    "severity",
    "message",
    "recommendation",
    "status",
    "source_id",
    "source_url",
    "source_type",
    "retrieved_at",
    "raw_path",
    "parser_version",
    "checksum",
    "run_id",
]

TASK_QUEUE_STANDARD_FIELDS = [
    "trade_date",
    "queue_id",
    "task_id",
    "queue_status",
    "priority",
    "created_at",
    "updated_at",
    "started_at",
    "finished_at",
    "message",
    "source_id",
    "source_url",
    "source_type",
    "retrieved_at",
    "raw_path",
    "parser_version",
    "checksum",
    "run_id",
]

TASK_LOGS_STANDARD_FIELDS = [
    "trade_date",
    "log_id",
    "task_id",
    "step_id",
    "level",
    "message",
    "created_at",
    "source_id",
    "source_url",
    "source_type",
    "retrieved_at",
    "raw_path",
    "parser_version",
    "checksum",
    "run_id",
]

TASK_RETRIES_STANDARD_FIELDS = [
    "trade_date",
    "retry_id",
    "task_id",
    "step_id",
    "retry_count",
    "status",
    "reason",
    "created_at",
    "source_id",
    "source_url",
    "source_type",
    "retrieved_at",
    "raw_path",
    "parser_version",
    "checksum",
    "run_id",
]

REPORT_INSIGHTS_STANDARD_FIELDS = [
    "trade_date",
    "insight_id",
    "task_id",
    "report_id",
    "insight_type",
    "title",
    "body",
    "severity",
    "status",
    "source_id",
    "source_url",
    "source_type",
    "retrieved_at",
    "raw_path",
    "parser_version",
    "checksum",
    "run_id",
]

RECOMMENDATION_ITEMS_STANDARD_FIELDS = [
    "trade_date",
    "recommendation_id",
    "task_id",
    "category",
    "title",
    "body",
    "priority",
    "status",
    "source_id",
    "source_url",
    "source_type",
    "retrieved_at",
    "raw_path",
    "parser_version",
    "checksum",
    "run_id",
]

MODEL_REGISTRY_STANDARD_FIELDS = [
    "trade_date",
    "model_id",
    "template_name",
    "dataset",
    "target_field",
    "feature_fields",
    "best_params",
    "score_metric",
    "score_value",
    "status",
    "reason",
    "source_id",
    "source_url",
    "source_type",
    "retrieved_at",
    "raw_path",
    "parser_version",
    "checksum",
    "run_id",
]

FEATURE_VERSIONS_STANDARD_FIELDS = [
    "trade_date",
    "feature_version_id",
    "dataset",
    "feature_names",
    "window_start",
    "window_end",
    "feature_count",
    "sample_count",
    "status",
    "reason",
    "source_id",
    "source_url",
    "source_type",
    "retrieved_at",
    "raw_path",
    "parser_version",
    "checksum",
    "run_id",
]

MODEL_DRIFT_EVENTS_STANDARD_FIELDS = [
    "trade_date",
    "drift_id",
    "model_id",
    "template_name",
    "dataset",
    "drift_metric",
    "baseline_value",
    "current_value",
    "drift_status",
    "severity",
    "message",
    "source_id",
    "source_url",
    "source_type",
    "retrieved_at",
    "raw_path",
    "parser_version",
    "checksum",
    "run_id",
]

SUPPORTED_INSTRUMENT_GROUPS = {"futures", "options", "all"}

SUCCESS_STATUS = "success"
PARTIAL_SUCCESS_STATUS = "partial_success"
NO_DATA_STATUS = "no_data"
ERROR_STATUS = "error"
PENDING_RETRY_STATUS = "pending_retry"
NOT_APPLICABLE_STATUS = "not_applicable"
FAILED_STATUS = "failed"

SUCCESS_LIKE_STATUSES = {SUCCESS_STATUS, PARTIAL_SUCCESS_STATUS}
