from dataclasses import dataclass, field
from typing import Dict, Iterable, List

from .constants import (
    ALGORITHM_OUTPUTS_DATASET,
    ANOMALY_EVENTS_DATASET,
    ARTIFACT_MANIFEST_DATASET,
    ASSET_COVERAGE_DATASET,
    BACKTEST_INPUT_QUALITY_DATASET,
    BACKTEST_EQUITY_CURVES_DATASET,
    BACKTEST_POSITIONS_DATASET,
    BACKTEST_TRADES_DATASET,
    COVERAGE_HISTORY_DATASET,
    CARBON_MARKET_SNAPSHOT_DATASET,
    BOND_ANALYTICS_DATASET,
    BOND_MASTER_DATASET,
    BOND_QUOTES_DATASET,
    CN_US_TREASURY_RATE_DATASET,
    CONTRACTS_DATASET,
    COMMODITY_SPOT_QUOTES_DATASET,
    CRYPTO_ASSETS_DATASET,
    CRYPTO_BITCOIN_HOLDINGS_DATASET,
    CRYPTO_CME_BITCOIN_REPORT_DATASET,
    CRYPTO_DAILY_QUOTES_DATASET,
    CRYPTO_DERIVATIVES_PUBLIC_DATASET,
    CRYPTO_GLOBAL_SNAPSHOT_DATASET,
    CRYPTO_GLOBAL_QUOTES_DATASET,
    DAILY_OHLCV_DATASET,
    DATASET_FIELD_PROFILE_DATASET,
    DATASET_INVENTORY_DATASET,
    DATASET_QUALITY_SCORES_DATASET,
    DATASET_SLA_RULES_DATASET,
    DATA_LINEAGE_DATASET,
    DERIVATIVES_DATASET,
    ETF_SNAPSHOT_DATASET,
    EQUITIES_SNAPSHOT_DATASET,
    FACTOR_EXPERIMENTS_DATASET,
    FACTOR_SIGNALS_DATASET,
    FACTOR_PERFORMANCE_DATASET,
    FX_QUOTES_DATASET,
    FX_C_SWAP_CURVE_DATASET,
    FX_PAIR_DATASET,
    FX_REFERENCE_DATASET,
    RMB_MIDDLE_RATE_DATASET,
    FUND_NAV_DATASET,
    ISSUE_CATEGORY_OVERVIEW_DATASET,
    INTERBANK_BOND_DEAL_DATASET,
    INTERBANK_BOND_QUOTE_DATASET,
    FUTURES_DATASET,
    FUTURES_RESULTS_DATASET,
    EXPERIMENT_RUNS_DATASET,
    LOF_SNAPSHOT_DATASET,
    LPR_REFERENCE_DATASET,
    FX_SPOT_DATASET,
    FX_SWAP_DATASET,
    MONEY_MARKET_DATASET,
    MONEY_FUND_SNAPSHOT_DATASET,
    KNOWLEDGE_INDEX_DATASET,
    ML_BENCHMARKS_DATASET,
    ML_CLASSIFICATION_RESULTS_DATASET,
    ML_FEATURE_IMPORTANCE_DATASET,
    ML_FEATURE_STORE_DATASET,
    ML_MODEL_RUNS_DATASET,
    ML_PREDICTIONS_DATASET,
    ML_VALIDATION_FOLDS_DATASET,
    MODEL_DIAGNOSTICS_DATASET,
    OPEN_FUND_SNAPSHOT_DATASET,
    OPTIONS_CHAIN_VIEW,
    OPTIONS_DATASET,
    OPTION_RESULTS_DATASET,
    OPTION_ANALYTICS_DATASET,
    PRECIOUS_METAL_REFERENCE_DATASET,
    RESERVE_REFERENCE_DATASET,
    REPO_REFERENCE_DATASET,
    REITS_QUOTES_DATASET,
    REPORT_ARTIFACTS_DATASET,
    RUN_HEALTH_DATASET,
    RUN_HISTORY_DATASET,
    PAPER_PORTFOLIOS_DATASET,
    PARAMETER_SCANS_DATASET,
    PORTFOLIO_ALLOCATIONS_DATASET,
    PORTFOLIO_EXPERIMENTS_DATASET,
    PROJECT_RUNS_DATASET,
    QUALITY_DIAGNOSTICS_DATASET,
    RESEARCH_METRICS_DATASET,
    RESEARCH_PROJECTS_DATASET,
    RESEARCH_REPORTS_DATASET,
    REPRODUCIBLE_PACKAGES_DATASET,
    AGENT_TASKS_DATASET,
    AGENT_STEPS_DATASET,
    PLUGIN_REGISTRY_DATASET,
    PLUGIN_RUNS_DATASET,
    RESEARCH_MEMORY_DATASET,
    EXPERIMENT_NOTES_DATASET,
    DECISION_LOG_DATASET,
    QUALITY_GATES_DATASET,
    RESEARCH_READINESS_DATASET,
    INPUT_RISK_FLAGS_DATASET,
    TASK_QUEUE_DATASET,
    TASK_LOGS_DATASET,
    TASK_RETRIES_DATASET,
    REPORT_INSIGHTS_DATASET,
    RECOMMENDATION_ITEMS_DATASET,
    MODEL_REGISTRY_DATASET,
    FEATURE_VERSIONS_DATASET,
    MODEL_DRIFT_EVENTS_DATASET,
    REITS_SNAPSHOT_DATASET,
    SGE_SPOT_DAILY_DATASET,
    SOURCE_HEALTH_DATASET,
    SOURCE_HEALTH_HISTORY_DATASET,
    SOURCE_TYPE_OVERVIEW_DATASET,
    SLA_VIOLATIONS_DATASET,
    SCHEDULER_RUNS_DATASET,
    SCENARIO_SIMULATIONS_DATASET,
    SSE_BOND_CASH_SUMMARY_DATASET,
    SSE_BOND_DEAL_SUMMARY_DATASET,
    STRATEGY_BACKTESTS_DATASET,
    STRATEGY_COMPARISONS_DATASET,
    STRATEGY_LEADERBOARD_DATASET,
    STRESS_TEST_RESULTS_DATASET,
    TRADING_CALENDAR_DATASET,
    UNDERLYING_SUMMARY_VIEW,
    BSE_EQUITIES_SNAPSHOT_DATASET,
    CONVERTIBLE_BOND_SNAPSHOT_DATASET,
    INSTRUMENT_MASTER_DATASET,
    VALIDATION_RESULTS_DATASET,
    YIELD_CURVE_DATASET,
    YIELD_CURVES_PLATFORM_DATASET,
    CURVE_ANALYTICS_DATASET,
    RISK_METRICS_DATASET,
)


@dataclass(frozen=True)
class AssetFamily:
    family_id: str
    label: str
    scope: str
    status: str
    phase: str
    implemented_datasets: List[str] = field(default_factory=list)
    markets: List[str] = field(default_factory=list)
    notes: str = ""

    def to_summary(self) -> Dict[str, object]:
        return {
            "family_id": self.family_id,
            "label": self.label,
            "scope": self.scope,
            "status": self.status,
            "phase": self.phase,
            "implemented_datasets": list(self.implemented_datasets),
            "markets": list(self.markets),
            "notes": self.notes,
        }


def build_asset_family_registry() -> List[AssetFamily]:
    return [
        AssetFamily(
            family_id="platform_metadata",
            label="平台元数据与质量",
            scope="统一 instrument master、validation 结果与 source health",
            status="implemented",
            phase="A/B/C",
            implemented_datasets=[
                INSTRUMENT_MASTER_DATASET,
                BOND_MASTER_DATASET,
                BOND_QUOTES_DATASET,
                FX_QUOTES_DATASET,
                COMMODITY_SPOT_QUOTES_DATASET,
                CRYPTO_GLOBAL_QUOTES_DATASET,
                DAILY_OHLCV_DATASET,
                FUND_NAV_DATASET,
                REITS_QUOTES_DATASET,
                TRADING_CALENDAR_DATASET,
                YIELD_CURVES_PLATFORM_DATASET,
                ASSET_COVERAGE_DATASET,
                COVERAGE_HISTORY_DATASET,
                RUN_HEALTH_DATASET,
                RUN_HISTORY_DATASET,
                VALIDATION_RESULTS_DATASET,
                SOURCE_HEALTH_DATASET,
                SOURCE_HEALTH_HISTORY_DATASET,
                SOURCE_TYPE_OVERVIEW_DATASET,
                ISSUE_CATEGORY_OVERVIEW_DATASET,
                RESEARCH_METRICS_DATASET,
                FACTOR_SIGNALS_DATASET,
                STRATEGY_BACKTESTS_DATASET,
                PAPER_PORTFOLIOS_DATASET,
                QUALITY_DIAGNOSTICS_DATASET,
                SCHEDULER_RUNS_DATASET,
                RESEARCH_REPORTS_DATASET,
                ALGORITHM_OUTPUTS_DATASET,
                OPTION_ANALYTICS_DATASET,
                BOND_ANALYTICS_DATASET,
                CURVE_ANALYTICS_DATASET,
                RISK_METRICS_DATASET,
                PORTFOLIO_ALLOCATIONS_DATASET,
                BACKTEST_EQUITY_CURVES_DATASET,
                BACKTEST_POSITIONS_DATASET,
                BACKTEST_TRADES_DATASET,
                STRATEGY_COMPARISONS_DATASET,
                ANOMALY_EVENTS_DATASET,
                ML_MODEL_RUNS_DATASET,
                ML_PREDICTIONS_DATASET,
                ML_FEATURE_IMPORTANCE_DATASET,
                MODEL_DIAGNOSTICS_DATASET,
                BACKTEST_INPUT_QUALITY_DATASET,
                EXPERIMENT_RUNS_DATASET,
                FACTOR_PERFORMANCE_DATASET,
                STRESS_TEST_RESULTS_DATASET,
                ARTIFACT_MANIFEST_DATASET,
                DATASET_QUALITY_SCORES_DATASET,
                REPORT_ARTIFACTS_DATASET,
                DATASET_INVENTORY_DATASET,
                DATASET_FIELD_PROFILE_DATASET,
                DATA_LINEAGE_DATASET,
                DATASET_SLA_RULES_DATASET,
                SLA_VIOLATIONS_DATASET,
                KNOWLEDGE_INDEX_DATASET,
                ML_FEATURE_STORE_DATASET,
                ML_BENCHMARKS_DATASET,
                ML_VALIDATION_FOLDS_DATASET,
                ML_CLASSIFICATION_RESULTS_DATASET,
                FACTOR_EXPERIMENTS_DATASET,
                PARAMETER_SCANS_DATASET,
                STRATEGY_LEADERBOARD_DATASET,
                PORTFOLIO_EXPERIMENTS_DATASET,
                SCENARIO_SIMULATIONS_DATASET,
                RESEARCH_PROJECTS_DATASET,
                PROJECT_RUNS_DATASET,
                REPRODUCIBLE_PACKAGES_DATASET,
                AGENT_TASKS_DATASET,
                AGENT_STEPS_DATASET,
                PLUGIN_REGISTRY_DATASET,
                PLUGIN_RUNS_DATASET,
                RESEARCH_MEMORY_DATASET,
                EXPERIMENT_NOTES_DATASET,
                DECISION_LOG_DATASET,
                QUALITY_GATES_DATASET,
                RESEARCH_READINESS_DATASET,
                INPUT_RISK_FLAGS_DATASET,
                TASK_QUEUE_DATASET,
                TASK_LOGS_DATASET,
                TASK_RETRIES_DATASET,
                REPORT_INSIGHTS_DATASET,
                RECOMMENDATION_ITEMS_DATASET,
                MODEL_REGISTRY_DATASET,
                FEATURE_VERSIONS_DATASET,
                MODEL_DRIFT_EVENTS_DATASET,
            ],
            markets=["LOCAL_DERIVED"],
            notes="由 canonical 输出、多资产状态文件和二期运行历史派生，不参与 query 覆盖 canonical，也不更新 contracts_latest。",
        ),
        AssetFamily(
            family_id="exchange_derivatives_cn",
            label="国内场内衍生品",
            scope="期货、期权、主数据、结果链、统一表、宽表视图",
            status="implemented",
            phase="A/B",
            implemented_datasets=[
                FUTURES_DATASET,
                OPTIONS_DATASET,
                DERIVATIVES_DATASET,
                CONTRACTS_DATASET,
                OPTION_RESULTS_DATASET,
                FUTURES_RESULTS_DATASET,
                OPTIONS_CHAIN_VIEW,
                UNDERLYING_SUMMARY_VIEW,
            ],
            markets=["SHFE", "INE", "CFFEX", "CZCE", "DCE", "GFEX", "SSE", "SZSE"],
            notes="当前仓库的正式 canonical 数据面板，已具备 query/canonical 隔离、完整性校验和修复流程。",
        ),
        AssetFamily(
            family_id="equities_funds_cn",
            label="股票、ETF、基金、REITs",
            scope="A 股、ETF、LOF、公募 REITs、指数、上市公司主数据",
            status="partially_implemented",
            phase="C",
            implemented_datasets=[
                "equities_spot_snapshot",
                "bse_equities_spot_snapshot",
                "etf_spot_snapshot",
                LOF_SNAPSHOT_DATASET,
                OPEN_FUND_SNAPSHOT_DATASET,
                MONEY_FUND_SNAPSHOT_DATASET,
                "reits_spot_snapshot",
                "convertible_bond_spot_snapshot",
                FUND_NAV_DATASET,
                REITS_QUOTES_DATASET,
            ],
            markets=["SSE", "SZSE", "BSE"],
            notes="当前已落地 A 股全市场快照、北交所股票快照、ETF / LOF / 开放式基金 / 货币基金快照、REITs 快照与可转债快照；更细的历史行情、主数据和结果链仍待继续扩展。",
        ),
        AssetFamily(
            family_id="bonds_rates_cn",
            label="债券与利率",
            scope="交易所债、银行间债、曲线、Shibor、DR、回购利率",
            status="partially_implemented",
            phase="C",
            implemented_datasets=[
                INTERBANK_BOND_DEAL_DATASET,
                INTERBANK_BOND_QUOTE_DATASET,
                YIELD_CURVE_DATASET,
                CN_US_TREASURY_RATE_DATASET,
                BOND_MASTER_DATASET,
                BOND_QUOTES_DATASET,
                LPR_REFERENCE_DATASET,
                REPO_REFERENCE_DATASET,
                SSE_BOND_DEAL_SUMMARY_DATASET,
                SSE_BOND_CASH_SUMMARY_DATASET,
            ],
            markets=["ChinaMoney", "CFETS", "中债", "SSE", "SZSE", "BSE"],
            notes="当前已接入银行间现券成交、做市报价、收益率曲线、LPR、回购利率，以及上交所债券成交/现券市场摘要；债券主数据、交易所债明细和更丰富曲线仍待继续扩展。",
        ),
        AssetFamily(
            family_id="fx_money_market_cn",
            label="外汇与货币市场",
            scope="人民币汇率中间价、即期、远期、掉期、货币市场公开参考数据",
            status="partially_implemented",
            phase="C",
            implemented_datasets=[
                FX_REFERENCE_DATASET,
                RMB_MIDDLE_RATE_DATASET,
                FX_SPOT_DATASET,
                FX_PAIR_DATASET,
                FX_SWAP_DATASET,
                FX_C_SWAP_CURVE_DATASET,
                FX_QUOTES_DATASET,
                MONEY_MARKET_DATASET,
                RESERVE_REFERENCE_DATASET,
            ],
            markets=["CFETS", "外汇局公开参考源"],
            notes="当前已接入人民币外汇参考价、人民币即期报价、外币对即期报价、人民币外汇远掉报价、USD/CNY C-Swap 定盘曲线、Shibor 参考表和外汇/黄金储备参考序列；更广的历史外汇与利率曲线仍待继续扩展。",
        ),
        AssetFamily(
            family_id="precious_metals_spot_cn",
            label="贵金属与现货基准",
            scope="上金所、上海金/银基准价、公开可得的大宗商品参考表",
            status="partially_implemented",
            phase="C",
            implemented_datasets=[PRECIOUS_METAL_REFERENCE_DATASET, SGE_SPOT_DAILY_DATASET, COMMODITY_SPOT_QUOTES_DATASET],
            markets=["SGE", "公开参考源"],
            notes="当前已接入上海金、上海银基准价参考表，以及上金所现货日行情；更完整的现货基准、租借利率和更多贵金属链路仍待继续扩展。",
        ),
        AssetFamily(
            family_id="commodity_energy_cn",
            label="商品、能源与碳市场",
            scope="国内公开可得的商品指数、能源参考表、碳市场快照",
            status="partially_implemented",
            phase="C",
            implemented_datasets=[CARBON_MARKET_SNAPSHOT_DATASET],
            markets=["全国碳市场 / 区域碳市场"],
            notes="当前已接入国内碳市场 as-of 快照；更多商品指数、能源参考表与现货链路仍待继续扩展。",
        ),
        AssetFamily(
            family_id="crypto_global_observation",
            label="全球加密资产观察",
            scope="全球公开行情观察模块，不含境内交易服务",
            status="partially_implemented",
            phase="C",
            implemented_datasets=[
                CRYPTO_GLOBAL_SNAPSHOT_DATASET,
                CRYPTO_ASSETS_DATASET,
                CRYPTO_DAILY_QUOTES_DATASET,
                CRYPTO_DERIVATIVES_PUBLIC_DATASET,
                CRYPTO_BITCOIN_HOLDINGS_DATASET,
                CRYPTO_CME_BITCOIN_REPORT_DATASET,
                CRYPTO_GLOBAL_QUOTES_DATASET,
            ],
            markets=["CoinGecko/CME 等公开源"],
            notes="当前已接入 CoinGecko 公共快照观察层；仅作研究与行情观察，不属于国内合法交易所 canonical 数据。",
        ),
    ]


def build_dataset_catalog() -> List[Dict[str, object]]:
    return [
        {
            "dataset": INSTRUMENT_MASTER_DATASET,
            "label": "统一 instrument master",
            "family_id": "platform_metadata",
            "scope": "derived canonical",
        },
        {
            "dataset": RUN_HEALTH_DATASET,
            "label": "统一回归健康表",
            "family_id": "platform_metadata",
            "scope": "derived quality",
        },
        {
            "dataset": RUN_HISTORY_DATASET,
            "label": "运行历史表",
            "family_id": "platform_metadata",
            "scope": "derived history",
        },
        {
            "dataset": RESEARCH_METRICS_DATASET,
            "label": "研究指标表",
            "family_id": "platform_metadata",
            "scope": "derived research",
        },
        {
            "dataset": FACTOR_SIGNALS_DATASET,
            "label": "因子信号表",
            "family_id": "platform_metadata",
            "scope": "derived research",
        },
        {
            "dataset": STRATEGY_BACKTESTS_DATASET,
            "label": "策略回测表",
            "family_id": "platform_metadata",
            "scope": "derived simulation",
        },
        {
            "dataset": PAPER_PORTFOLIOS_DATASET,
            "label": "模拟交易组合表",
            "family_id": "platform_metadata",
            "scope": "derived simulation",
        },
        {
            "dataset": QUALITY_DIAGNOSTICS_DATASET,
            "label": "质量诊断表",
            "family_id": "platform_metadata",
            "scope": "derived quality",
        },
        {
            "dataset": SCHEDULER_RUNS_DATASET,
            "label": "本地调度运行表",
            "family_id": "platform_metadata",
            "scope": "derived operations",
        },
        {
            "dataset": RESEARCH_REPORTS_DATASET,
            "label": "研究报告索引表",
            "family_id": "platform_metadata",
            "scope": "derived reports",
        },
        {
            "dataset": ALGORITHM_OUTPUTS_DATASET,
            "label": "统一算法输出表",
            "family_id": "platform_metadata",
            "scope": "derived algorithms",
        },
        {
            "dataset": OPTION_ANALYTICS_DATASET,
            "label": "期权金融数学分析表",
            "family_id": "platform_metadata",
            "scope": "derived option analytics",
        },
        {
            "dataset": BOND_ANALYTICS_DATASET,
            "label": "债券金融数学分析表",
            "family_id": "platform_metadata",
            "scope": "derived bond analytics",
        },
        {
            "dataset": CURVE_ANALYTICS_DATASET,
            "label": "收益率曲线分析表",
            "family_id": "platform_metadata",
            "scope": "derived curve analytics",
        },
        {
            "dataset": RISK_METRICS_DATASET,
            "label": "组合风险指标表",
            "family_id": "platform_metadata",
            "scope": "derived risk",
        },
        {
            "dataset": PORTFOLIO_ALLOCATIONS_DATASET,
            "label": "组合配置权重表",
            "family_id": "platform_metadata",
            "scope": "derived portfolio",
        },
        {
            "dataset": BACKTEST_EQUITY_CURVES_DATASET,
            "label": "正式回测净值曲线表",
            "family_id": "platform_metadata",
            "scope": "derived backtest",
        },
        {
            "dataset": BACKTEST_POSITIONS_DATASET,
            "label": "正式回测持仓明细表",
            "family_id": "platform_metadata",
            "scope": "derived backtest",
        },
        {
            "dataset": BACKTEST_TRADES_DATASET,
            "label": "正式回测交易明细表",
            "family_id": "platform_metadata",
            "scope": "derived backtest",
        },
        {
            "dataset": STRATEGY_COMPARISONS_DATASET,
            "label": "策略对比指标表",
            "family_id": "platform_metadata",
            "scope": "derived backtest",
        },
        {
            "dataset": ANOMALY_EVENTS_DATASET,
            "label": "数据异常事件表",
            "family_id": "platform_metadata",
            "scope": "derived quality",
        },
        {
            "dataset": ML_MODEL_RUNS_DATASET,
            "label": "机器学习模型运行表",
            "family_id": "platform_metadata",
            "scope": "derived ml",
        },
        {
            "dataset": ML_PREDICTIONS_DATASET,
            "label": "机器学习预测明细表",
            "family_id": "platform_metadata",
            "scope": "derived ml",
        },
        {
            "dataset": ML_FEATURE_IMPORTANCE_DATASET,
            "label": "机器学习特征重要性表",
            "family_id": "platform_metadata",
            "scope": "derived ml",
        },
        {
            "dataset": MODEL_DIAGNOSTICS_DATASET,
            "label": "模型诊断表",
            "family_id": "platform_metadata",
            "scope": "derived ml",
        },
        {
            "dataset": BACKTEST_INPUT_QUALITY_DATASET,
            "label": "回测输入质量表",
            "family_id": "platform_metadata",
            "scope": "derived quality",
        },
        {
            "dataset": EXPERIMENT_RUNS_DATASET,
            "label": "实验运行追踪表",
            "family_id": "platform_metadata",
            "scope": "derived experiments",
        },
        {
            "dataset": FACTOR_PERFORMANCE_DATASET,
            "label": "因子表现评估表",
            "family_id": "platform_metadata",
            "scope": "derived factor analytics",
        },
        {
            "dataset": STRESS_TEST_RESULTS_DATASET,
            "label": "组合压力测试表",
            "family_id": "platform_metadata",
            "scope": "derived risk",
        },
        {
            "dataset": ARTIFACT_MANIFEST_DATASET,
            "label": "研究产物血缘表",
            "family_id": "platform_metadata",
            "scope": "derived lineage",
        },
        {
            "dataset": DATASET_QUALITY_SCORES_DATASET,
            "label": "数据集质量评分表",
            "family_id": "platform_metadata",
            "scope": "derived quality",
        },
        {
            "dataset": REPORT_ARTIFACTS_DATASET,
            "label": "报告图表附件表",
            "family_id": "platform_metadata",
            "scope": "derived reports",
        },
        {
            "dataset": BOND_MASTER_DATASET,
            "label": "统一债券主数据",
            "family_id": "bonds_rates_cn",
            "scope": "derived latest-view",
        },
        {
            "dataset": INTERBANK_BOND_DEAL_DATASET,
            "label": "银行间债券成交快照",
            "family_id": "bonds_rates_cn",
            "scope": "latest snapshot",
        },
        {
            "dataset": INTERBANK_BOND_QUOTE_DATASET,
            "label": "银行间债券报价快照",
            "family_id": "bonds_rates_cn",
            "scope": "latest snapshot",
        },
        {
            "dataset": BOND_QUOTES_DATASET,
            "label": "统一债券报价表",
            "family_id": "bonds_rates_cn",
            "scope": "derived latest-view",
        },
        {
            "dataset": FX_QUOTES_DATASET,
            "label": "统一外汇报价表",
            "family_id": "fx_money_market_cn",
            "scope": "derived latest-view",
        },
        {
            "dataset": FX_REFERENCE_DATASET,
            "label": "人民币外汇参考价",
            "family_id": "fx_money_market_cn",
            "scope": "latest reference",
        },
        {
            "dataset": RMB_MIDDLE_RATE_DATASET,
            "label": "人民币汇率中间价参考表",
            "family_id": "fx_money_market_cn",
            "scope": "normalized latest-view",
        },
        {
            "dataset": FX_SPOT_DATASET,
            "label": "人民币即期报价",
            "family_id": "fx_money_market_cn",
            "scope": "latest snapshot",
        },
        {
            "dataset": FX_PAIR_DATASET,
            "label": "外币对即期报价",
            "family_id": "fx_money_market_cn",
            "scope": "latest snapshot",
        },
        {
            "dataset": FX_SWAP_DATASET,
            "label": "人民币外汇远掉报价",
            "family_id": "fx_money_market_cn",
            "scope": "latest snapshot",
        },
        {
            "dataset": FX_C_SWAP_CURVE_DATASET,
            "label": "USD/CNY C-Swap 曲线",
            "family_id": "fx_money_market_cn",
            "scope": "latest curve",
        },
        {
            "dataset": MONEY_MARKET_DATASET,
            "label": "货币市场利率参考表",
            "family_id": "fx_money_market_cn",
            "scope": "latest reference",
        },
        {
            "dataset": RESERVE_REFERENCE_DATASET,
            "label": "外汇与黄金储备参考序列",
            "family_id": "fx_money_market_cn",
            "scope": "historical reference",
        },
        {
            "dataset": COMMODITY_SPOT_QUOTES_DATASET,
            "label": "统一现货与基准价表",
            "family_id": "precious_metals_spot_cn",
            "scope": "derived latest-view",
        },
        {
            "dataset": PRECIOUS_METAL_REFERENCE_DATASET,
            "label": "上海金银基准价参考表",
            "family_id": "precious_metals_spot_cn",
            "scope": "latest reference",
        },
        {
            "dataset": SGE_SPOT_DAILY_DATASET,
            "label": "上金所现货日行情",
            "family_id": "precious_metals_spot_cn",
            "scope": "latest snapshot",
        },
        {
            "dataset": CARBON_MARKET_SNAPSHOT_DATASET,
            "label": "全国碳市场快照",
            "family_id": "commodity_energy_cn",
            "scope": "latest snapshot",
        },
        {
            "dataset": CRYPTO_GLOBAL_QUOTES_DATASET,
            "label": "统一全球加密报价表",
            "family_id": "crypto_global_observation",
            "scope": "derived latest-view",
        },
        {
            "dataset": CRYPTO_GLOBAL_SNAPSHOT_DATASET,
            "label": "全球加密快照",
            "family_id": "crypto_global_observation",
            "scope": "latest snapshot",
        },
        {
            "dataset": DAILY_OHLCV_DATASET,
            "label": "统一日线行情表",
            "family_id": "platform_metadata",
            "scope": "derived latest-view",
        },
        {
            "dataset": FUND_NAV_DATASET,
            "label": "统一基金净值表",
            "family_id": "equities_funds_cn",
            "scope": "derived latest-view",
        },
        {
            "dataset": EQUITIES_SNAPSHOT_DATASET,
            "label": "A 股全市场快照",
            "family_id": "equities_funds_cn",
            "scope": "latest snapshot",
        },
        {
            "dataset": BSE_EQUITIES_SNAPSHOT_DATASET,
            "label": "北交所股票快照",
            "family_id": "equities_funds_cn",
            "scope": "latest snapshot",
        },
        {
            "dataset": ETF_SNAPSHOT_DATASET,
            "label": "ETF 快照",
            "family_id": "equities_funds_cn",
            "scope": "latest snapshot",
        },
        {
            "dataset": LOF_SNAPSHOT_DATASET,
            "label": "LOF 快照",
            "family_id": "equities_funds_cn",
            "scope": "latest snapshot",
        },
        {
            "dataset": OPEN_FUND_SNAPSHOT_DATASET,
            "label": "开放式基金净值快照",
            "family_id": "equities_funds_cn",
            "scope": "latest snapshot",
        },
        {
            "dataset": MONEY_FUND_SNAPSHOT_DATASET,
            "label": "货币基金快照",
            "family_id": "equities_funds_cn",
            "scope": "latest snapshot",
        },
        {
            "dataset": REITS_SNAPSHOT_DATASET,
            "label": "REITs 快照",
            "family_id": "equities_funds_cn",
            "scope": "latest snapshot",
        },
        {
            "dataset": CONVERTIBLE_BOND_SNAPSHOT_DATASET,
            "label": "可转债快照",
            "family_id": "equities_funds_cn",
            "scope": "latest snapshot",
        },
        {
            "dataset": REITS_QUOTES_DATASET,
            "label": "统一 REITs 行情表",
            "family_id": "equities_funds_cn",
            "scope": "derived latest-view",
        },
        {
            "dataset": TRADING_CALENDAR_DATASET,
            "label": "统一交易日日历快照",
            "family_id": "platform_metadata",
            "scope": "derived latest-view",
        },
        {
            "dataset": YIELD_CURVES_PLATFORM_DATASET,
            "label": "统一收益率曲线表",
            "family_id": "bonds_rates_cn",
            "scope": "derived latest-view",
        },
        {
            "dataset": YIELD_CURVE_DATASET,
            "label": "收益率曲线点位快照",
            "family_id": "bonds_rates_cn",
            "scope": "latest curve",
        },
        {
            "dataset": CN_US_TREASURY_RATE_DATASET,
            "label": "中美国债收益率参考表",
            "family_id": "bonds_rates_cn",
            "scope": "latest reference",
        },
        {
            "dataset": LPR_REFERENCE_DATASET,
            "label": "LPR 参考表",
            "family_id": "bonds_rates_cn",
            "scope": "latest reference",
        },
        {
            "dataset": REPO_REFERENCE_DATASET,
            "label": "回购利率参考表",
            "family_id": "bonds_rates_cn",
            "scope": "latest reference",
        },
        {
            "dataset": SSE_BOND_DEAL_SUMMARY_DATASET,
            "label": "上交所债券成交摘要",
            "family_id": "bonds_rates_cn",
            "scope": "latest snapshot",
        },
        {
            "dataset": SSE_BOND_CASH_SUMMARY_DATASET,
            "label": "上交所现券市场摘要",
            "family_id": "bonds_rates_cn",
            "scope": "latest snapshot",
        },
        {
            "dataset": ASSET_COVERAGE_DATASET,
            "label": "资产覆盖总览",
            "family_id": "platform_metadata",
            "scope": "derived overview",
        },
        {
            "dataset": COVERAGE_HISTORY_DATASET,
            "label": "资产覆盖历史表",
            "family_id": "platform_metadata",
            "scope": "derived history",
        },
        {
            "dataset": VALIDATION_RESULTS_DATASET,
            "label": "统一 validation 结果",
            "family_id": "platform_metadata",
            "scope": "derived canonical",
        },
        {
            "dataset": SOURCE_HEALTH_DATASET,
            "label": "统一 source health",
            "family_id": "platform_metadata",
            "scope": "derived canonical",
        },
        {
            "dataset": SOURCE_HEALTH_HISTORY_DATASET,
            "label": "source health 历史表",
            "family_id": "platform_metadata",
            "scope": "derived history",
        },
        {
            "dataset": SOURCE_TYPE_OVERVIEW_DATASET,
            "label": "源类型运行总览",
            "family_id": "platform_metadata",
            "scope": "derived overview",
        },
        {
            "dataset": ISSUE_CATEGORY_OVERVIEW_DATASET,
            "label": "问题类别运行总览",
            "family_id": "platform_metadata",
            "scope": "derived overview",
        },
        {
            "dataset": FUTURES_DATASET,
            "label": "期货日行情",
            "family_id": "exchange_derivatives_cn",
            "scope": "canonical / query",
        },
        {
            "dataset": OPTIONS_DATASET,
            "label": "期权日行情",
            "family_id": "exchange_derivatives_cn",
            "scope": "canonical / query",
        },
        {
            "dataset": DERIVATIVES_DATASET,
            "label": "统一衍生品总表",
            "family_id": "exchange_derivatives_cn",
            "scope": "canonical(all) / query",
        },
        {
            "dataset": CONTRACTS_DATASET,
            "label": "合约主数据快照",
            "family_id": "exchange_derivatives_cn",
            "scope": "canonical(all) / query",
        },
        {
            "dataset": OPTION_RESULTS_DATASET,
            "label": "期权行权结果",
            "family_id": "exchange_derivatives_cn",
            "scope": "canonical / query",
        },
        {
            "dataset": FUTURES_RESULTS_DATASET,
            "label": "期货交割结果",
            "family_id": "exchange_derivatives_cn",
            "scope": "canonical / query",
        },
        {
            "dataset": OPTIONS_CHAIN_VIEW,
            "label": "期权链矩阵视图",
            "family_id": "exchange_derivatives_cn",
            "scope": "canonical(all/options) / query",
        },
        {
            "dataset": UNDERLYING_SUMMARY_VIEW,
            "label": "标的衍生品汇总视图",
            "family_id": "exchange_derivatives_cn",
            "scope": "canonical(all) / query",
        },
        {
            "dataset": CRYPTO_ASSETS_DATASET,
            "label": "全球加密资产清单",
            "family_id": "crypto_global_observation",
            "scope": "latest/cached",
        },
        {
            "dataset": CRYPTO_BITCOIN_HOLDINGS_DATASET,
            "label": "全球公开比特币持仓参考",
            "family_id": "crypto_global_observation",
            "scope": "latest/cached",
        },
        {
            "dataset": CRYPTO_CME_BITCOIN_REPORT_DATASET,
            "label": "CME 比特币公开报告",
            "family_id": "crypto_global_observation",
            "scope": "historical/latest-when-published",
        },
        {
            "dataset": CRYPTO_DAILY_QUOTES_DATASET,
            "label": "全球加密日线快照",
            "family_id": "crypto_global_observation",
            "scope": "latest/historical-by-public-history",
        },
        {
            "dataset": CRYPTO_DERIVATIVES_PUBLIC_DATASET,
            "label": "全球加密衍生品公开参考",
            "family_id": "crypto_global_observation",
            "scope": "latest/cached",
        },
    ]


def family_status_counts(families: Iterable[AssetFamily]) -> Dict[str, int]:
    counts: Dict[str, int] = {}
    for family in families:
        counts[family.status] = counts.get(family.status, 0) + 1
    return counts
