from typing import Dict, List

from .config import load_sources_config
from .constants import (
    ALGORITHM_OUTPUTS_DATASET,
    ANOMALY_EVENTS_DATASET,
    ARTIFACT_MANIFEST_DATASET,
    ASSET_COVERAGE_DATASET,
    BACKTEST_INPUT_QUALITY_DATASET,
    BACKTEST_EQUITY_CURVES_DATASET,
    BACKTEST_POSITIONS_DATASET,
    BACKTEST_TRADES_DATASET,
    BOND_ANALYTICS_DATASET,
    COVERAGE_HISTORY_DATASET,
    BOND_MASTER_DATASET,
    BOND_QUOTES_DATASET,
    BSE_EQUITIES_SNAPSHOT_DATASET,
    CARBON_MARKET_SNAPSHOT_DATASET,
    CN_US_TREASURY_RATE_DATASET,
    COMMODITY_SPOT_QUOTES_DATASET,
    CONVERTIBLE_BOND_SNAPSHOT_DATASET,
    CRYPTO_ASSETS_DATASET,
    CRYPTO_BITCOIN_HOLDINGS_DATASET,
    CRYPTO_CME_BITCOIN_REPORT_DATASET,
    CRYPTO_DAILY_QUOTES_DATASET,
    CRYPTO_DERIVATIVES_PUBLIC_DATASET,
    CRYPTO_GLOBAL_QUOTES_DATASET,
    CRYPTO_GLOBAL_SNAPSHOT_DATASET,
    DAILY_OHLCV_DATASET,
    DATASET_FIELD_PROFILE_DATASET,
    DATASET_INVENTORY_DATASET,
    DATASET_QUALITY_SCORES_DATASET,
    DATASET_SLA_RULES_DATASET,
    DATA_LINEAGE_DATASET,
    ETF_SNAPSHOT_DATASET,
    EQUITIES_SNAPSHOT_DATASET,
    EXPERIMENT_RUNS_DATASET,
    FACTOR_EXPERIMENTS_DATASET,
    FACTOR_SIGNALS_DATASET,
    FACTOR_PERFORMANCE_DATASET,
    FX_C_SWAP_CURVE_DATASET,
    FX_PAIR_DATASET,
    FX_REFERENCE_DATASET,
    RMB_MIDDLE_RATE_DATASET,
    FX_QUOTES_DATASET,
    FX_SPOT_DATASET,
    FUND_NAV_DATASET,
    ISSUE_CATEGORY_OVERVIEW_DATASET,
    INSTRUMENT_MASTER_DATASET,
    INTERBANK_BOND_DEAL_DATASET,
    INTERBANK_BOND_QUOTE_DATASET,
    LOF_SNAPSHOT_DATASET,
    LPR_REFERENCE_DATASET,
    MONEY_FUND_SNAPSHOT_DATASET,
    MONEY_MARKET_DATASET,
    KNOWLEDGE_INDEX_DATASET,
    ML_BENCHMARKS_DATASET,
    ML_CLASSIFICATION_RESULTS_DATASET,
    ML_FEATURE_IMPORTANCE_DATASET,
    ML_FEATURE_STORE_DATASET,
    ML_MODEL_RUNS_DATASET,
    ML_PREDICTIONS_DATASET,
    ML_VALIDATION_FOLDS_DATASET,
    MODEL_DIAGNOSTICS_DATASET,
    OPEN_FUND_SNAPSHOT_DATASET,
    FX_SWAP_DATASET,
    FUTURES_RESULTS_DATASET,
    CURVE_ANALYTICS_DATASET,
    PAPER_PORTFOLIOS_DATASET,
    PARAMETER_SCANS_DATASET,
    PORTFOLIO_ALLOCATIONS_DATASET,
    PORTFOLIO_EXPERIMENTS_DATASET,
    PROJECT_RUNS_DATASET,
    PRECIOUS_METAL_REFERENCE_DATASET,
    QUALITY_DIAGNOSTICS_DATASET,
    OPTION_RESULTS_DATASET,
    OPTION_ANALYTICS_DATASET,
    RESEARCH_METRICS_DATASET,
    RESEARCH_PROJECTS_DATASET,
    RESEARCH_REPORTS_DATASET,
    REPRODUCIBLE_PACKAGES_DATASET,
    REPORT_ARTIFACTS_DATASET,
    RESERVE_REFERENCE_DATASET,
    REITS_QUOTES_DATASET,
    RUN_HEALTH_DATASET,
    RUN_HISTORY_DATASET,
    REITS_SNAPSHOT_DATASET,
    REPO_REFERENCE_DATASET,
    SGE_SPOT_DAILY_DATASET,
    SOURCE_HEALTH_DATASET,
    SOURCE_HEALTH_HISTORY_DATASET,
    SOURCE_TYPE_OVERVIEW_DATASET,
    SLA_VIOLATIONS_DATASET,
    SCHEDULER_RUNS_DATASET,
    SCENARIO_SIMULATIONS_DATASET,
    SSE_BOND_CASH_SUMMARY_DATASET,
    SSE_BOND_DEAL_SUMMARY_DATASET,
    STRATEGY_BACKTESTS_DATASET,
    STRATEGY_COMPARISONS_DATASET,
    STRATEGY_LEADERBOARD_DATASET,
    STRESS_TEST_RESULTS_DATASET,
    TRADING_CALENDAR_DATASET,
    VALIDATION_RESULTS_DATASET,
    YIELD_CURVE_DATASET,
    YIELD_CURVES_PLATFORM_DATASET,
    RISK_METRICS_DATASET,
    AGENT_TASKS_DATASET,
    AGENT_STEPS_DATASET,
    PLUGIN_REGISTRY_DATASET,
    PLUGIN_RUNS_DATASET,
    RESEARCH_MEMORY_DATASET,
    EXPERIMENT_NOTES_DATASET,
    DECISION_LOG_DATASET,
    QUALITY_GATES_DATASET,
    RESEARCH_READINESS_DATASET,
    INPUT_RISK_FLAGS_DATASET,
    TASK_QUEUE_DATASET,
    TASK_LOGS_DATASET,
    TASK_RETRIES_DATASET,
    REPORT_INSIGHTS_DATASET,
    RECOMMENDATION_ITEMS_DATASET,
    MODEL_REGISTRY_DATASET,
    FEATURE_VERSIONS_DATASET,
    MODEL_DRIFT_EVENTS_DATASET,
)
from .exercise_results import SSE_OPTION_EXERCISE_URL, SZSE_OPTION_EXERCISE_URL


def build_source_catalog() -> List[Dict[str, object]]:
    settings = load_sources_config()
    catalog: List[Dict[str, object]] = []

    for exchange_id, exchange_settings in settings.get("exchanges", {}).items():
        catalog.append(
            {
                "source_id": f"{exchange_id.lower()}.futures",
                "asset_family": "exchange_derivatives_cn",
                "market": "cn_futures",
                "exchange": exchange_id,
                "dataset": "futures_daily_quotes",
                "source_type": "official",
                "priority": 1,
                "url": exchange_settings.get("daily_url")
                or exchange_settings.get("json_url")
                or exchange_settings.get("txt_url")
                or exchange_settings.get("api_url")
                or exchange_settings.get("bootstrap_url", ""),
            }
        )
        catalog.append(
            {
                "source_id": f"{exchange_id.lower()}.futures_delivery_results",
                "asset_family": "exchange_derivatives_cn",
                "market": "cn_futures",
                "exchange": exchange_id,
                "dataset": FUTURES_RESULTS_DATASET,
                "source_type": "official",
                "priority": 2,
                "url": exchange_settings.get("monthly_delivery_results_url")
                or exchange_settings.get("monthly_market_report_reference_url")
                or exchange_settings.get("delivery_results_url")
                or "",
            }
        )
        if exchange_id == "SHFE":
            catalog.append(
                {
                    "source_id": "ine.futures_delivery_results",
                    "asset_family": "exchange_derivatives_cn",
                    "market": "cn_futures",
                    "exchange": "INE",
                    "dataset": FUTURES_RESULTS_DATASET,
                    "source_type": "official",
                    "priority": 2,
                "url": exchange_settings.get("monthly_delivery_results_url")
                    or exchange_settings.get("monthly_market_report_reference_url")
                    or exchange_settings.get("delivery_results_url")
                    or "",
                }
            )

    option_catalog = [
        ("SHFE", "exchange_derivatives_cn", "cn_options", "options_daily_quotes", "official"),
        ("CFFEX", "exchange_derivatives_cn", "cn_options", "options_daily_quotes", "official"),
        ("CZCE", "exchange_derivatives_cn", "cn_options", "options_daily_quotes", "official"),
        ("GFEX", "exchange_derivatives_cn", "cn_options", "options_daily_quotes", "official"),
        ("DCE", "exchange_derivatives_cn", "cn_options", "options_daily_quotes", "official_browser_bootstrap"),
        ("SSE", "exchange_derivatives_cn", "cn_options", "options_daily_quotes", "official"),
        ("SZSE", "exchange_derivatives_cn", "cn_options", "options_daily_quotes", "official"),
    ]
    for exchange, asset_family, market, dataset, source_type in option_catalog:
        catalog.append(
            {
                "source_id": f"{exchange.lower()}.options",
                "asset_family": asset_family,
                "market": market,
                "exchange": exchange,
                "dataset": dataset,
                "source_type": source_type,
                "priority": 1,
                "url": "",
            }
        )
        catalog.append(
            {
                "source_id": f"{exchange.lower()}.options_exercise_results",
                "asset_family": asset_family,
                "market": market,
                "exchange": exchange,
                "dataset": OPTION_RESULTS_DATASET,
                "source_type": "official",
                "priority": 2,
                "url": (
                    SSE_OPTION_EXERCISE_URL
                    if exchange == "SSE"
                    else SZSE_OPTION_EXERCISE_URL
                    if exchange == "SZSE"
                    else settings.get("exchanges", {}).get("DCE", {}).get("monthly_market_report_reference_url", "")
                    if exchange == "DCE"
                    else ""
                ),
            }
        )

    public_entries = [
        (EQUITIES_SNAPSHOT_DATASET, "equities_funds_cn", "cn_equities", "SSE/SZSE", "fallback_online", "https://vip.stock.finance.sina.com.cn/mkt/#hs_a"),
        (BSE_EQUITIES_SNAPSHOT_DATASET, "equities_funds_cn", "cn_equities", "BSE", "fallback_online", "https://qt.gtimg.cn/"),
        (ETF_SNAPSHOT_DATASET, "equities_funds_cn", "cn_etf", "SSE/SZSE", "fallback_online", "https://fund.10jqka.com.cn/datacenter/jz/kfs/etf/"),
        (LOF_SNAPSHOT_DATASET, "equities_funds_cn", "cn_funds", "SSE/SZSE", "fallback_online", "https://hq.sinajs.cn/"),
        (OPEN_FUND_SNAPSHOT_DATASET, "equities_funds_cn", "cn_funds", "CN_FUNDS", "fallback_online", "https://fund.eastmoney.com/fund.html#os_0;isall_0;ft_;pt_1"),
        (MONEY_FUND_SNAPSHOT_DATASET, "equities_funds_cn", "cn_funds", "CN_FUNDS", "fallback_online", "https://fund.eastmoney.com/HBJJ_pjsyl.html"),
        (REITS_SNAPSHOT_DATASET, "equities_funds_cn", "cn_reits", "SSE/SZSE", "fallback_online", "https://hq.sinajs.cn/"),
        (CONVERTIBLE_BOND_SNAPSHOT_DATASET, "bonds_rates_cn", "cn_exchange_bonds", "SSE/SZSE", "fallback_online", "https://quote.eastmoney.com/center/gridlist.html#convertible_bond"),
        (SGE_SPOT_DAILY_DATASET, "precious_metals_spot_cn", "sge_spot", "SGE", "fallback_online", "https://www.sge.com.cn/sjzx/mrhq"),
        (CARBON_MARKET_SNAPSHOT_DATASET, "commodity_energy_cn", "cn_carbon", "全国碳市场/区域市场", "fallback_online", "http://www.tanjiaoyi.com/"),
        (FX_REFERENCE_DATASET, "fx_money_market_cn", "cn_fx_reference", "BOC", "fallback_online", "https://www.boc.cn/sourcedb/whpj/"),
        (RMB_MIDDLE_RATE_DATASET, "fx_money_market_cn", "cn_rmb_central_parity", "PBOC", "fallback_online", "https://datacenter.jin10.com/reportType/dc_rmb_data"),
        (FX_SPOT_DATASET, "fx_money_market_cn", "cn_fx_spot", "CFETS", "fallback_online", "http://www.chinamoney.com.cn/chinese/mkdatapfx/"),
        (FX_PAIR_DATASET, "fx_money_market_cn", "cn_fx_pair", "CFETS", "fallback_online", "http://www.chinamoney.com.cn/chinese/mkdatapfx/"),
        (FX_SWAP_DATASET, "fx_money_market_cn", "cn_fx_swap", "CFETS", "fallback_online", "http://www.chinamoney.com.cn/chinese/mkdatapfx/"),
        (FX_C_SWAP_CURVE_DATASET, "fx_money_market_cn", "cn_fx_swap_curve", "CFETS", "fallback_online", "https://www.chinamoney.org.cn/chinese/bkcurvfsw"),
        (MONEY_MARKET_DATASET, "fx_money_market_cn", "cn_money_market", "SHIBOR", "fallback_online", "https://www.shibor.org/shibor/web/html/shibor.html"),
        (RESERVE_REFERENCE_DATASET, "fx_money_market_cn", "cn_reserve_reference", "SAFE/PBOC", "fallback_online", "https://data.eastmoney.com/cjsj/hjwh.html"),
        (LPR_REFERENCE_DATASET, "bonds_rates_cn", "cn_lpr", "LPR", "fallback_online", "https://www.chinamoney.com.cn/chinese/bkccpr/"),
        (REPO_REFERENCE_DATASET, "bonds_rates_cn", "cn_repo_reference", "CFETS", "fallback_online", "https://www.chinamoney.com.cn/chinese/bkcurvexrr/"),
        (CN_US_TREASURY_RATE_DATASET, "bonds_rates_cn", "cross_market_treasury_yield", "EASTMONEY", "fallback_online", "https://data.eastmoney.com/cjsj/zmgzsyl.html"),
        (PRECIOUS_METAL_REFERENCE_DATASET, "precious_metals_spot_cn", "sge_benchmark", "SGE", "fallback_online", "https://www.sge.com.cn/"),
        (INTERBANK_BOND_DEAL_DATASET, "bonds_rates_cn", "cn_interbank_bond", "CFETS", "fallback_online", "https://www.chinamoney.com.cn/chinese/mkdatabond/"),
        (INTERBANK_BOND_QUOTE_DATASET, "bonds_rates_cn", "cn_interbank_bond", "CFETS", "fallback_online", "https://www.chinamoney.com.cn/chinese/mkdatabond/"),
        (YIELD_CURVE_DATASET, "bonds_rates_cn", "cn_yield_curve", "CHINABOND", "fallback_online", "https://yield.chinabond.com.cn/"),
        (SSE_BOND_DEAL_SUMMARY_DATASET, "bonds_rates_cn", "cn_exchange_bonds", "SSE", "fallback_online", "http://bond.sse.com.cn/data/statistics/overview/turnover/"),
        (SSE_BOND_CASH_SUMMARY_DATASET, "bonds_rates_cn", "cn_exchange_bonds", "SSE", "fallback_online", "http://bond.sse.com.cn/data/statistics/overview/bondow/"),
        (CRYPTO_GLOBAL_SNAPSHOT_DATASET, "crypto_global_observation", "crypto_global_market_data", "COINGECKO", "fallback_online", "https://www.coingecko.com/"),
        (CRYPTO_ASSETS_DATASET, "crypto_global_observation", "crypto_global_market_data", "COINGECKO", "fallback_online", "https://www.coingecko.com/"),
        (CRYPTO_DAILY_QUOTES_DATASET, "crypto_global_observation", "crypto_global_market_data", "COINGECKO", "fallback_online", "https://www.coingecko.com/"),
        (CRYPTO_DERIVATIVES_PUBLIC_DATASET, "crypto_global_observation", "crypto_derivatives_public", "COINGECKO/CME_PUBLIC/OKX_PUBLIC", "fallback_online", "https://www.okx.com/api/v5/market/tickers?instType=SWAP"),
        (CRYPTO_BITCOIN_HOLDINGS_DATASET, "crypto_global_observation", "crypto_public_bitcoin_holdings", "AKSHARE", "fallback_online", "https://crypto-akshare.akfamily.xyz/data/crypto/crypto.html"),
        (CRYPTO_CME_BITCOIN_REPORT_DATASET, "crypto_global_observation", "crypto_cme_public_report", "CME/JIN10", "fallback_online", "https://datacenter.jin10.com/reportType/dc_cme_btc_report"),
    ]
    for dataset, asset_family, market, exchange, source_type, url in public_entries:
        catalog.append(
            {
                "source_id": dataset,
                "asset_family": asset_family,
                "market": market,
                "exchange": exchange,
                "dataset": dataset,
                "source_type": source_type,
                "priority": 10,
                "url": url,
            }
        )

    platform_entries = [
        (INSTRUMENT_MASTER_DATASET, "platform_metadata", "platform_unified", "DERIVED", "derived", "platform://instrument_master"),
        (BOND_MASTER_DATASET, "platform_metadata", "platform_unified", "DERIVED", "derived", "platform://bond_master"),
        (BOND_QUOTES_DATASET, "platform_metadata", "platform_unified", "DERIVED", "derived", "platform://bond_quotes"),
        (FX_QUOTES_DATASET, "platform_metadata", "platform_unified", "DERIVED", "derived", "platform://fx_quotes"),
        (COMMODITY_SPOT_QUOTES_DATASET, "platform_metadata", "platform_unified", "DERIVED", "derived", "platform://commodity_spot_quotes"),
        (CRYPTO_GLOBAL_QUOTES_DATASET, "platform_metadata", "platform_unified", "DERIVED", "derived", "platform://crypto_global_quotes"),
        (DAILY_OHLCV_DATASET, "platform_metadata", "platform_unified", "DERIVED", "derived", "platform://daily_ohlcv"),
        (FUND_NAV_DATASET, "platform_metadata", "platform_unified", "DERIVED", "derived", "platform://fund_nav"),
        (REITS_QUOTES_DATASET, "platform_metadata", "platform_unified", "DERIVED", "derived", "platform://reits_quotes"),
        (TRADING_CALENDAR_DATASET, "platform_metadata", "platform_unified", "DERIVED", "derived", "platform://trading_calendar"),
        (YIELD_CURVES_PLATFORM_DATASET, "platform_metadata", "platform_unified", "DERIVED", "derived", "platform://yield_curves"),
        (ASSET_COVERAGE_DATASET, "platform_metadata", "platform_overview", "DERIVED", "derived", "platform://asset_coverage"),
        (VALIDATION_RESULTS_DATASET, "platform_metadata", "platform_quality", "DERIVED", "derived", "platform://validation_results"),
        (SOURCE_HEALTH_DATASET, "platform_metadata", "platform_quality", "DERIVED", "derived", "platform://source_health"),
        (SOURCE_HEALTH_HISTORY_DATASET, "platform_metadata", "platform_quality", "DERIVED", "derived", "platform://source_health_history"),
        (SOURCE_TYPE_OVERVIEW_DATASET, "platform_metadata", "platform_quality", "DERIVED", "derived", "platform://source_type_overview"),
        (ISSUE_CATEGORY_OVERVIEW_DATASET, "platform_metadata", "platform_quality", "DERIVED", "derived", "platform://issue_category_overview"),
        (RUN_HEALTH_DATASET, "platform_metadata", "platform_quality", "DERIVED", "derived", "platform://run_health"),
        (RUN_HISTORY_DATASET, "platform_metadata", "platform_quality", "DERIVED", "derived", "platform://run_history"),
        (COVERAGE_HISTORY_DATASET, "platform_metadata", "platform_quality", "DERIVED", "derived", "platform://coverage_history"),
        (RESEARCH_METRICS_DATASET, "platform_metadata", "platform_research", "DERIVED", "derived", "platform://research_metrics"),
        (FACTOR_SIGNALS_DATASET, "platform_metadata", "platform_research", "DERIVED", "derived", "platform://factor_signals"),
        (STRATEGY_BACKTESTS_DATASET, "platform_metadata", "platform_research", "DERIVED", "derived", "platform://strategy_backtests"),
        (PAPER_PORTFOLIOS_DATASET, "platform_metadata", "platform_research", "DERIVED", "derived", "platform://paper_portfolios"),
        (QUALITY_DIAGNOSTICS_DATASET, "platform_metadata", "platform_quality", "DERIVED", "derived", "platform://quality_diagnostics"),
        (SCHEDULER_RUNS_DATASET, "platform_metadata", "platform_operations", "DERIVED", "derived", "platform://scheduler_runs"),
        (RESEARCH_REPORTS_DATASET, "platform_metadata", "platform_reports", "DERIVED", "derived", "platform://research_reports"),
        (ALGORITHM_OUTPUTS_DATASET, "platform_metadata", "platform_algorithms", "DERIVED", "derived", "platform://algorithm_outputs"),
        (OPTION_ANALYTICS_DATASET, "platform_metadata", "platform_algorithms", "DERIVED", "derived", "platform://option_analytics"),
        (BOND_ANALYTICS_DATASET, "platform_metadata", "platform_algorithms", "DERIVED", "derived", "platform://bond_analytics"),
        (CURVE_ANALYTICS_DATASET, "platform_metadata", "platform_algorithms", "DERIVED", "derived", "platform://curve_analytics"),
        (RISK_METRICS_DATASET, "platform_metadata", "platform_risk", "DERIVED", "derived", "platform://risk_metrics"),
        (PORTFOLIO_ALLOCATIONS_DATASET, "platform_metadata", "platform_portfolio", "DERIVED", "derived", "platform://portfolio_allocations"),
        (BACKTEST_EQUITY_CURVES_DATASET, "platform_metadata", "platform_backtest", "DERIVED", "derived", "platform://backtest_equity_curves"),
        (BACKTEST_POSITIONS_DATASET, "platform_metadata", "platform_backtest", "DERIVED", "derived", "platform://backtest_positions"),
        (BACKTEST_TRADES_DATASET, "platform_metadata", "platform_backtest", "DERIVED", "derived", "platform://backtest_trades"),
        (STRATEGY_COMPARISONS_DATASET, "platform_metadata", "platform_backtest", "DERIVED", "derived", "platform://strategy_comparisons"),
        (ANOMALY_EVENTS_DATASET, "platform_metadata", "platform_quality", "DERIVED", "derived", "platform://anomaly_events"),
        (ML_MODEL_RUNS_DATASET, "platform_metadata", "platform_ml", "DERIVED", "derived", "platform://ml_model_runs"),
        (ML_PREDICTIONS_DATASET, "platform_metadata", "platform_ml", "DERIVED", "derived", "platform://ml_predictions"),
        (ML_FEATURE_IMPORTANCE_DATASET, "platform_metadata", "platform_ml", "DERIVED", "derived", "platform://ml_feature_importance"),
        (MODEL_DIAGNOSTICS_DATASET, "platform_metadata", "platform_ml", "DERIVED", "derived", "platform://model_diagnostics"),
        (BACKTEST_INPUT_QUALITY_DATASET, "platform_metadata", "platform_quality", "DERIVED", "derived", "platform://backtest_input_quality"),
        (EXPERIMENT_RUNS_DATASET, "platform_metadata", "platform_experiments", "DERIVED", "derived", "platform://experiment_runs"),
        (FACTOR_PERFORMANCE_DATASET, "platform_metadata", "platform_factor_analytics", "DERIVED", "derived", "platform://factor_performance"),
        (STRESS_TEST_RESULTS_DATASET, "platform_metadata", "platform_risk", "DERIVED", "derived", "platform://stress_test_results"),
        (ARTIFACT_MANIFEST_DATASET, "platform_metadata", "platform_lineage", "DERIVED", "derived", "platform://artifact_manifest"),
        (DATASET_QUALITY_SCORES_DATASET, "platform_metadata", "platform_quality", "DERIVED", "derived", "platform://dataset_quality_scores"),
        (REPORT_ARTIFACTS_DATASET, "platform_metadata", "platform_reports", "DERIVED", "derived", "platform://report_artifacts"),
        (DATASET_INVENTORY_DATASET, "platform_metadata", "platform_inventory", "DERIVED", "derived", "platform://dataset_inventory"),
        (DATASET_FIELD_PROFILE_DATASET, "platform_metadata", "platform_inventory", "DERIVED", "derived", "platform://dataset_field_profile"),
        (DATA_LINEAGE_DATASET, "platform_metadata", "platform_lineage", "DERIVED", "derived", "platform://data_lineage"),
        (DATASET_SLA_RULES_DATASET, "platform_metadata", "platform_operations", "DERIVED", "derived", "platform://dataset_sla_rules"),
        (SLA_VIOLATIONS_DATASET, "platform_metadata", "platform_operations", "DERIVED", "derived", "platform://sla_violations"),
        (KNOWLEDGE_INDEX_DATASET, "platform_metadata", "platform_knowledge", "DERIVED", "derived", "platform://knowledge_index"),
        (ML_FEATURE_STORE_DATASET, "platform_metadata", "platform_ml", "DERIVED", "derived", "platform://ml_feature_store"),
        (ML_BENCHMARKS_DATASET, "platform_metadata", "platform_ml", "DERIVED", "derived", "platform://ml_benchmarks"),
        (ML_VALIDATION_FOLDS_DATASET, "platform_metadata", "platform_ml", "DERIVED", "derived", "platform://ml_validation_folds"),
        (ML_CLASSIFICATION_RESULTS_DATASET, "platform_metadata", "platform_ml", "DERIVED", "derived", "platform://ml_classification_results"),
        (FACTOR_EXPERIMENTS_DATASET, "platform_metadata", "platform_factor_analytics", "DERIVED", "derived", "platform://factor_experiments"),
        (PARAMETER_SCANS_DATASET, "platform_metadata", "platform_factor_analytics", "DERIVED", "derived", "platform://parameter_scans"),
        (STRATEGY_LEADERBOARD_DATASET, "platform_metadata", "platform_backtest", "DERIVED", "derived", "platform://strategy_leaderboard"),
        (PORTFOLIO_EXPERIMENTS_DATASET, "platform_metadata", "platform_portfolio", "DERIVED", "derived", "platform://portfolio_experiments"),
        (SCENARIO_SIMULATIONS_DATASET, "platform_metadata", "platform_risk", "DERIVED", "derived", "platform://scenario_simulations"),
        (RESEARCH_PROJECTS_DATASET, "platform_metadata", "platform_projects", "DERIVED", "derived", "platform://research_projects"),
        (PROJECT_RUNS_DATASET, "platform_metadata", "platform_projects", "DERIVED", "derived", "platform://project_runs"),
        (REPRODUCIBLE_PACKAGES_DATASET, "platform_metadata", "platform_projects", "DERIVED", "derived", "platform://reproducible_packages"),
        (AGENT_TASKS_DATASET, "platform_metadata", "platform_agent", "DERIVED", "derived", "platform://agent_tasks"),
        (AGENT_STEPS_DATASET, "platform_metadata", "platform_agent", "DERIVED", "derived", "platform://agent_steps"),
        (PLUGIN_REGISTRY_DATASET, "platform_metadata", "platform_agent", "DERIVED", "derived", "platform://plugin_registry"),
        (PLUGIN_RUNS_DATASET, "platform_metadata", "platform_agent", "DERIVED", "derived", "platform://plugin_runs"),
        (RESEARCH_MEMORY_DATASET, "platform_metadata", "platform_agent", "DERIVED", "derived", "platform://research_memory"),
        (EXPERIMENT_NOTES_DATASET, "platform_metadata", "platform_agent", "DERIVED", "derived", "platform://experiment_notes"),
        (DECISION_LOG_DATASET, "platform_metadata", "platform_agent", "DERIVED", "derived", "platform://decision_log"),
        (QUALITY_GATES_DATASET, "platform_metadata", "platform_agent", "DERIVED", "derived", "platform://quality_gates"),
        (RESEARCH_READINESS_DATASET, "platform_metadata", "platform_agent", "DERIVED", "derived", "platform://research_readiness"),
        (INPUT_RISK_FLAGS_DATASET, "platform_metadata", "platform_agent", "DERIVED", "derived", "platform://input_risk_flags"),
        (TASK_QUEUE_DATASET, "platform_metadata", "platform_agent", "DERIVED", "derived", "platform://task_queue"),
        (TASK_LOGS_DATASET, "platform_metadata", "platform_agent", "DERIVED", "derived", "platform://task_logs"),
        (TASK_RETRIES_DATASET, "platform_metadata", "platform_agent", "DERIVED", "derived", "platform://task_retries"),
        (REPORT_INSIGHTS_DATASET, "platform_metadata", "platform_agent", "DERIVED", "derived", "platform://report_insights"),
        (RECOMMENDATION_ITEMS_DATASET, "platform_metadata", "platform_agent", "DERIVED", "derived", "platform://recommendation_items"),
        (MODEL_REGISTRY_DATASET, "platform_metadata", "platform_agent", "DERIVED", "derived", "platform://model_registry"),
        (FEATURE_VERSIONS_DATASET, "platform_metadata", "platform_agent", "DERIVED", "derived", "platform://feature_versions"),
        (MODEL_DRIFT_EVENTS_DATASET, "platform_metadata", "platform_agent", "DERIVED", "derived", "platform://model_drift_events"),
    ]
    for dataset, asset_family, market, exchange, source_type, url in platform_entries:
        catalog.append(
            {
                "source_id": dataset,
                "asset_family": asset_family,
                "market": market,
                "exchange": exchange,
                "dataset": dataset,
                "source_type": source_type,
                "priority": 100,
                "url": url,
            }
        )
    return catalog
